-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.workforce Service

CREATE TABLE IF NOT EXISTS departments (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    department_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_masters (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    department_id UUID NOT NULL REFERENCES departments(id),
    manager_hr_id UUID REFERENCES employee_masters(id),
    org_depth_level VARCHAR(255) NOT NULL,
    employee_number VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    base_salary NUMERIC(15, 4) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payroll_runs (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    fiscal_year VARCHAR(255) NOT NULL,
    period_number VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_gross_pay NUMERIC(15, 4) NOT NULL,
    total_deductions NUMERIC(15, 4) NOT NULL,
    total_net_pay NUMERIC(15, 4) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_claims (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    employee_id UUID NOT NULL REFERENCES employee_masters(id),
    claim_number VARCHAR(255) NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    cost_center_tag VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_claim_lines (
    id UUID PRIMARY KEY NOT NULL,
    expense_claim_id UUID NOT NULL REFERENCES expense_claims(id),
    description TEXT NOT NULL,
    line_amount NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    attempt_count VARCHAR(255) NOT NULL
);

