-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for HR Service

CREATE TABLE IF NOT EXISTS departments (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    manager_id UUID,
    parent_dept_id UUID REFERENCES departments(id),
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    department_id UUID NOT NULL REFERENCES departments(id),
    min_salary NUMERIC(15, 4) NOT NULL,
    max_salary NUMERIC(15, 4) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
    id UUID PRIMARY KEY NOT NULL,
    employee_id VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(255) NOT NULL,
    hire_date DATE NOT NULL,
    term_date DATE,
    department_id UUID NOT NULL REFERENCES departments(id),
    position_id UUID NOT NULL REFERENCES positions(id),
    manager_id UUID REFERENCES employees(id),
    status VARCHAR(255) NOT NULL,
    salary NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_compensation_histories (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    salary NUMERIC(15, 4) NOT NULL,
    effective_date DATE NOT NULL,
    changed_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll_records (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    pay_period_start DATE NOT NULL,
    pay_period_end DATE NOT NULL,
    regular_hours NUMERIC(15, 4) NOT NULL,
    overtime_hours NUMERIC(15, 4) NOT NULL,
    gross_pay NUMERIC(15, 4) NOT NULL,
    net_pay NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll_deductions (
    id UUID PRIMARY KEY NOT NULL,
    payroll_id UUID NOT NULL REFERENCES payroll_records(id),
    type VARCHAR(255) NOT NULL,
    amount NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance_entries (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    entry_date DATE NOT NULL,
    clock_in TIMESTAMP NOT NULL,
    clock_out TIMESTAMP NOT NULL,
    total_hours NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    project_id UUID REFERENCES projects(id),
    task_id UUID REFERENCES tasks(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    leave_type VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    approved_by UUID REFERENCES employees(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS leave_balances (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    leave_type VARCHAR(255) NOT NULL,
    entitled_days NUMERIC(15, 4) NOT NULL,
    used_days NUMERIC(15, 4) NOT NULL,
    year INT NOT NULL
);

CREATE TABLE IF NOT EXISTS job_postings (
    id UUID PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    department_id UUID NOT NULL REFERENCES departments(id),
    location VARCHAR(255) NOT NULL,
    salary_range VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS job_applications (
    id UUID PRIMARY KEY NOT NULL,
    job_posting_id UUID NOT NULL REFERENCES job_postings(id),
    applicant_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    resume_url VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS performance_reviews (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    reviewer_id UUID NOT NULL REFERENCES employees(id),
    review_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    rating INT NOT NULL,
    rating_scale VARCHAR(255) NOT NULL,
    feedback VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS training_programs (
    id UUID PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    trainer VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS training_enrollments (
    id UUID PRIMARY KEY NOT NULL,
    training_id UUID NOT NULL REFERENCES training_programs(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    enrolled_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_documents (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    doc_type VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_claims (
    id UUID PRIMARY KEY NOT NULL,
    employee_id UUID NOT NULL REFERENCES employees(id),
    claim_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_claim_lines (
    id UUID PRIMARY KEY NOT NULL,
    claim_id UUID NOT NULL REFERENCES expense_claims(id),
    description TEXT NOT NULL,
    amount NUMERIC(15, 4) NOT NULL
);

