// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Department struct {
	ID             string    `json:"id"`
	LegalEntityID  string    `json:"legal_entity_id"` // Primitive Ref -> FM.LegalEntity (Loose Link)
	DepartmentCode string    `json:"department_code"` // Unique within tenant boundary (e.g., "DEPT_ENG")
	Name           string    `json:"name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
