// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Department struct {
	ID           string    `json:"id"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	ManagerID    *string   `json:"manager_id"`
	ParentDeptID *string   `json:"parent_dept_id"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
