// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type EmployeeCompensationHistory struct {
	ID            string          `json:"id"`
	EmployeeID    string          `json:"employee_id"`
	Salary        decimal.Decimal `json:"salary"`
	EffectiveDate time.Time       `json:"effective_date"`
	ChangedBy     string          `json:"changed_by"` // Auth User ID reference
	CreatedAt     time.Time       `json:"created_at"`
}
