// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type EmployeeDocument struct {
	ID         string    `json:"id"`
	EmployeeID string    `json:"employee_id"`
	DocType    string    `json:"doc_type"` // e.g., CONTRACT, ID_PROOF, CERTIFICATE
	FileName   string    `json:"file_name"`
	FileUrl    string    `json:"file_url"`
	UploadedAt time.Time `json:"uploaded_at"`
}
