// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type EmployeeMaster struct {
	ID             string          `json:"id"`
	LegalEntityID  string          `json:"legal_entity_id"` // Strict multi-tenant data isolation shield
	DepartmentID   string          `json:"department_id"`
	ManagerHrID    *string         `json:"manager_hr_id,omitempty"`
	OrgDepthLevel  int             `json:"org_depth_level"` // Root level = 0, line management increments sequentially
	EmployeeNumber string          `json:"employee_number"` // Corporate ID token scoped within tenant
	FirstName      string          `json:"first_name"`
	LastName       string          `json:"last_name"`
	Email          string          `json:"email"`
	Status         EmployeeStatus  `json:"status"`
	Type           EmploymentType  `json:"type"`
	BaseSalary     decimal.Decimal `json:"base_salary"`
	Version        int             `json:"version"` // Concurrency Shield for GORM modifications
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	DeletedAt      *time.Time      `json:"deleted_at,omitempty"` // GORM Native Soft Delete Support
}
