// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Employee struct {
	ID           string          `json:"id"`
	EmployeeID   string          `json:"employee_id"`
	FirstName    string          `json:"first_name"`
	LastName     string          `json:"last_name"`
	Email        string          `json:"email"`
	Phone        string          `json:"phone"`
	HireDate     time.Time       `json:"hire_date"`
	TermDate     *time.Time      `json:"term_date"`
	DepartmentID string          `json:"department_id"`
	PositionID   string          `json:"position_id"`
	ManagerID    *string         `json:"manager_id"`
	Status       string          `json:"status"` // e.g., ACTIVE, TERMINATED, LEAVE
	Salary       decimal.Decimal `json:"salary"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
