// Code generated by CDD Engine. DO NOT EDIT.
package domain

// EmployeeStatus represents the EmployeeStatus enum
type EmployeeStatus string

const (
	EmployeeStatusACTIVE     EmployeeStatus = "ACTIVE"
	EmployeeStatusON_LEAVE   EmployeeStatus = "ON_LEAVE"
	EmployeeStatusTERMINATED EmployeeStatus = "TERMINATED"
)

// IsValid returns true if the EmployeeStatus is valid
func (e EmployeeStatus) IsValid() bool {
	switch e {
	case EmployeeStatusACTIVE:
		return true
	case EmployeeStatusON_LEAVE:
		return true
	case EmployeeStatusTERMINATED:
		return true
	}
	return false
}

// EmploymentType represents the EmploymentType enum
type EmploymentType string

const (
	EmploymentTypeFULL_TIME  EmploymentType = "FULL_TIME"
	EmploymentTypePART_TIME  EmploymentType = "PART_TIME"
	EmploymentTypeCONTRACTOR EmploymentType = "CONTRACTOR"
)

// IsValid returns true if the EmploymentType is valid
func (e EmploymentType) IsValid() bool {
	switch e {
	case EmploymentTypeFULL_TIME:
		return true
	case EmploymentTypePART_TIME:
		return true
	case EmploymentTypeCONTRACTOR:
		return true
	}
	return false
}

// PayrollStatus represents the PayrollStatus enum
type PayrollStatus string

const (
	PayrollStatusDRAFT     PayrollStatus = "DRAFT"
	PayrollStatusAPPROVED  PayrollStatus = "APPROVED"
	PayrollStatusPROCESSED PayrollStatus = "PROCESSED"
	PayrollStatusFAILED    PayrollStatus = "FAILED"
)

// IsValid returns true if the PayrollStatus is valid
func (e PayrollStatus) IsValid() bool {
	switch e {
	case PayrollStatusDRAFT:
		return true
	case PayrollStatusAPPROVED:
		return true
	case PayrollStatusPROCESSED:
		return true
	case PayrollStatusFAILED:
		return true
	}
	return false
}

// ExpenseStatus represents the ExpenseStatus enum
type ExpenseStatus string

const (
	ExpenseStatusSUBMITTED ExpenseStatus = "SUBMITTED"
	ExpenseStatusREVIEWED  ExpenseStatus = "REVIEWED"
	ExpenseStatusAPPROVED  ExpenseStatus = "APPROVED"
	ExpenseStatusREJECTED  ExpenseStatus = "REJECTED"
	ExpenseStatusPAID      ExpenseStatus = "PAID"
)

// IsValid returns true if the ExpenseStatus is valid
func (e ExpenseStatus) IsValid() bool {
	switch e {
	case ExpenseStatusSUBMITTED:
		return true
	case ExpenseStatusREVIEWED:
		return true
	case ExpenseStatusAPPROVED:
		return true
	case ExpenseStatusREJECTED:
		return true
	case ExpenseStatusPAID:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
