// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicHrEmployeeCreated              = "hr.employee.created"
	TopicHrEmployeeUpdated              = "hr.employee.updated"
	TopicHrEmployeeTerminated           = "hr.employee.terminated"
	TopicHrEmployeePromoted             = "hr.employee.promoted"
	TopicHrPayrollProcessed             = "hr.payroll.processed"
	TopicHrPayrollFailed                = "hr.payroll.failed"
	TopicHrSalaryChanged                = "hr.salary.changed"
	TopicHrTimesheetSubmitted           = "hr.timesheet.submitted"
	TopicHrTimesheetApproved            = "hr.timesheet.approved"
	TopicHrOvertimeRecorded             = "hr.overtime.recorded"
	TopicHrLeaveRequested               = "hr.leave.requested"
	TopicHrLeaveApproved                = "hr.leave.approved"
	TopicHrLeaveRejected                = "hr.leave.rejected"
	TopicHrTrainingCompleted            = "hr.training.completed"
	TopicHrCertificationEarned          = "hr.certification.earned"
	TopicHrSkillAcquired                = "hr.skill.acquired"
	TopicHrPerformanceReviewCompleted   = "hr.performance.review.completed"
	TopicHrGoalAchieved                 = "hr.goal.achieved"
	TopicHrPerformanceImprovementNeeded = "hr.performance.improvement.needed"

	// Consumer Events
	TopicPrjProjectCreated      = "prj.project.created"
	TopicPrjTaskAssigned        = "prj.task.assigned"
	TopicFinBudgetAllocated     = "fin.budget.allocated"
	TopicMfgProductionScheduled = "mfg.production.scheduled"
	TopicScmTrainingRequired    = "scm.training.required"
)
