// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicHrEmployeeCreated    = "hr.employee.created"
	TopicHrEmployeeTerminated = "hr.employee.terminated"
	TopicHrPayrollProcessed   = "hr.payroll.processed"
	TopicHrExpenseApproved    = "hr.expense.approved"

	// Consumer Events
	TopicPrjTimeLogged = "prj.time.logged"
	TopicFmVendorPaid  = "fm.vendor.paid"
)
