// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// ExpenseClaimLineInput represents the event payload for ExpenseClaimLineInput
type ExpenseClaimLineInput struct {
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
}
