// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type ExpenseClaimLine struct {
	ID             string          `json:"id"`
	ExpenseClaimID string          `json:"expense_claim_id"`
	Description    string          `json:"description"`
	LineAmount     decimal.Decimal `json:"line_amount"`
	CreatedAt      time.Time       `json:"created_at"`
}
