// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type ExpenseClaimLine struct {
	ID          string          `json:"id"`
	ClaimID     string          `json:"claim_id"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
}
