// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type ExpenseClaim struct {
	ID          string          `json:"id"`
	EmployeeID  string          `json:"employee_id"`
	ClaimDate   time.Time       `json:"claim_date"`
	Status      string          `json:"status"` // e.g., DRAFT, SUBMITTED, APPROVED, REJECTED
	TotalAmount decimal.Decimal `json:"total_amount"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
