// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type JobPosting struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	DepartmentID string    `json:"department_id"`
	Location     string    `json:"location"`
	SalaryRange  string    `json:"salary_range"`
	Status       string    `json:"status"` // e.g., DRAFT, OPEN, CLOSED
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
