// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type JobApplication struct {
	ID            string    `json:"id"`
	JobPostingID  string    `json:"job_posting_id"`
	ApplicantName string    `json:"applicant_name"`
	Email         string    `json:"email"`
	Phone         string    `json:"phone"`
	ResumeUrl     string    `json:"resume_url"`
	Status        string    `json:"status"` // e.g., APPLIED, SCREENING, INTERVIEW, OFFER, REJECTED
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
