// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type LeaveRequest struct {
	ID         string    `json:"id"`
	EmployeeID string    `json:"employee_id"`
	LeaveType  string    `json:"leave_type"` // e.g., ANNUAL, SICK, UNPAID
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
	Reason     string    `json:"reason"`
	Status     string    `json:"status"` // e.g., PENDING, APPROVED, REJECTED
	ApprovedBy *string   `json:"approved_by"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
