// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type LeaveBalance struct {
	ID           string          `json:"id"`
	EmployeeID   string          `json:"employee_id"`
	LeaveType    string          `json:"leave_type"`
	EntitledDays decimal.Decimal `json:"entitled_days"`
	UsedDays     decimal.Decimal `json:"used_days"`
	Year         int             `json:"year"`
}
