// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PayrollRun struct {
	ID              string          `json:"id"`
	LegalEntityID   string          `json:"legal_entity_id"`
	FiscalYear      int             `json:"fiscal_year"`
	PeriodNumber    int             `json:"period_number"` // Calendar Month 1 through 12
	Status          PayrollStatus   `json:"status"`
	TotalGrossPay   decimal.Decimal `json:"total_gross_pay"`
	TotalDeductions decimal.Decimal `json:"total_deductions"`
	TotalNetPay     decimal.Decimal `json:"total_net_pay"` // Transmitted to FM for cash disbursal tracking
	Version         int             `json:"version"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
