// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type PayrollRecord struct {
	ID             string          `json:"id"`
	EmployeeID     string          `json:"employee_id"`
	PayPeriodStart time.Time       `json:"pay_period_start"`
	PayPeriodEnd   time.Time       `json:"pay_period_end"`
	RegularHours   decimal.Decimal `json:"regular_hours"`
	OvertimeHours  decimal.Decimal `json:"overtime_hours"`
	GrossPay       decimal.Decimal `json:"gross_pay"`
	NetPay         decimal.Decimal `json:"net_pay"`
	Status         string          `json:"status"` // e.g., DRAFT, APPROVED, PAID
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
