// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type PayrollDeduction struct {
	ID        string          `json:"id"`
	PayrollID string          `json:"payroll_id"`
	Type      string          `json:"type"`
	Amount    decimal.Decimal `json:"amount"`
}
