// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type Position struct {
	ID           string          `json:"id"`
	Code         string          `json:"code"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	DepartmentID string          `json:"department_id"`
	MinSalary    decimal.Decimal `json:"min_salary"`
	MaxSalary    decimal.Decimal `json:"max_salary"`
	IsActive     bool            `json:"is_active"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
