// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type TimeEntry struct {
	ID         string          `json:"id"`
	EmployeeID string          `json:"employee_id"`
	EntryDate  time.Time       `json:"entry_date"`
	ClockIn    time.Time       `json:"clock_in"`
	ClockOut   time.Time       `json:"clock_out"`
	TotalHours decimal.Decimal `json:"total_hours"`
	Notes      string          `json:"notes"`
	Status     string          `json:"status"` // e.g., SUBMITTED, APPROVED, REJECTED
	ProjectID  *string         `json:"project_id"`
	TaskID     *string         `json:"task_id"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
