// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TrainingEnrollment struct {
	ID          string     `json:"id"`
	TrainingID  string     `json:"training_id"`
	EmployeeID  string     `json:"employee_id"`
	EnrolledAt  time.Time  `json:"enrolled_at"`
	CompletedAt *time.Time `json:"completed_at"`
	Status      string     `json:"status"`
}
