// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TrainingProgram struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Trainer     string    `json:"trainer"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	Status      string    `json:"status"` // e.g., SCHEDULED, ACTIVE, COMPLETED
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
