// Code generated by CDD Engine. DO NOT EDIT.
package domain

import ()

// CreateUserInput represents the event payload for CreateUserInput
type CreateUserInput struct {
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
	FirstName      string   `json:"first_name"`
	LastName       string   `json:"last_name"`
	LegalEntityID  string   `json:"legal_entity_id"`
	InitialStoreID *string  `json:"initial_store_id,omitempty"`
	RoleIds        []string `json:"role_ids"`
}
