// Code generated by CDD Engine. DO NOT EDIT.
package domain

// UserStatus represents the UserStatus enum
type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusINACTIVE  UserStatus = "INACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

// IsValid returns true if the UserStatus is valid
func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusACTIVE:
		return true
	case UserStatusINACTIVE:
		return true
	case UserStatusSUSPENDED:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
