// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicAuthUserCreated       = "auth.user.created"
	TopicAuthUserDeactivated   = "auth.user.deactivated"
	TopicAuthUserRoleAssigned  = "auth.user.role.assigned"
	TopicAuthUserStoreAssigned = "auth.user.store.assigned"
	TopicAuthPasswordChanged   = "auth.password.changed"
)
