// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type KafkaEventInbox struct {
	EventID          string                `json:"event_id"`   // Kafka message key — idempotency deduplication token
	EventType        string                `json:"event_type"` // e.g., "hr.employee.terminated"
	ProcessedAt      time.Time             `json:"processed_at"`
	ProcessingStatus EventProcessingStatus `json:"processing_status"`
	Payload          interface{}           `json:"payload"` // Inbound event payload archived for audit replay
}
