// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Permission struct {
	ID          string    `json:"id"`
	Code        string    `json:"code"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
