// Code generated by CDD Engine. DO NOT EDIT.
package domain

import ()

type RolePermission struct {
	ID           string `json:"id"`
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}
