// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

// TokenClaims represents the event payload for TokenClaims
type TokenClaims struct {
	UserID        string    `json:"user_id"`
	LegalEntityID string    `json:"legal_entity_id"`
	Roles         []string  `json:"roles"`
	Permissions   []string  `json:"permissions"`
	ExpiresAt     time.Time `json:"expires_at"`
}
