// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TransactionalOutbox struct {
	ID          string       `json:"id"`
	EventType   string       `json:"event_type"`   // e.g., "auth.user.created"
	AggregateID string       `json:"aggregate_id"` // User.id or Role.id context token
	Payload     interface{}  `json:"payload"`      // Fully serialized outbound event message
	Status      OutboxStatus `json:"status"`       // Polled by OutboxRelayWorker goroutine
	RetryCount  int          `json:"retry_count"`  // Protects relay worker from poison-pill loops
	CreatedAt   time.Time    `json:"created_at"`
}
