// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type UserStore struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	StoreID    string    `json:"store_id"`
	AssignedAt time.Time `json:"assigned_at"`
}
