// File: docker-compose.yml (Updated with Auth Service and API Gateway)
version: '3.8'
services:
  # Infrastructure
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - erp-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - erp-network

  # API Gateway (Entry Point)
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-super-secret-key
      - AUTH_SERVICE_URL=http://auth-service:8090
      - FM_SERVICE_URL=http://fm-service:8081
      - HR_SERVICE_URL=http://hr-service:8082
      - SCM_SERVICE_URL=http://scm-service:8083
      - M_SERVICE_URL=http://m-service:8084
      - CRM_SERVICE_URL=http://crm-service:8085
      - PM_SERVICE_URL=http://pm-service:8086
    depends_on:
      - auth-service
      - fm-service
    networks:
      - erp-network

  # Authentication Service
  auth-service:
    build: ./services/auth-service
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=erp_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-super-secret-key
    depends_on:
      - postgres
      - redis
    networks:
      - erp-network

  # Financial Management Service
  fm-service:
    build: ./services/financial-management
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=erp_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - erp-network

  # HR Service
  hr-service:
    build: ./services/hr-hcm
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - erp-network

  # Supply Chain Management Service
  scm-service:
    build: ./services/supply-chain-management
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - erp-network

  # Manufacturing Service
  m-service:
    build: ./services/manufacturing
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - erp-network

  # CRM Service
  crm-service:
    build: ./services/sales-crm
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - erp-network

  # Project Management Service
  pm-service:
    build: ./services/project-management
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - erp-network

volumes:
  postgres_data:

networks:
  erp-network:
    driver: bridge