# docker-compose.yml
version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: erp-api-gateway
    environment:
      - PORT=8080
      - FINANCE_SERVICE_URL=http://finance-service:8001
      - HR_SERVICE_URL=http://hr-service:8002
      - SCM_SERVICE_URL=http://scm-service:8003
      - MANUFACTURING_SERVICE_URL=http://manufacturing-service:8004
      - CRM_SERVICE_URL=http://crm-service:8005
      - PROJECTS_SERVICE_URL=http://projects-service:8006
    ports:
      - "8080:8080"
    networks:
      - erp-network
    restart: unless-stopped

  # Finance Service
  finance-service:
    build:
      context: .
      dockerfile: services/fm-service/Dockerfile
    container_name: erp-finance-service
    environment:
      - PORT=8001
      - SERVICE_NAME=finance
    ports:
      - "8001:8001"
    networks:
      - erp-network
    restart: unless-stopped

  # HR Service
  hr-service:
    build:
      context: .
      dockerfile: services/hr-service/Dockerfile
    container_name: erp-hr-service
    environment:
      - PORT=8002
      - SERVICE_NAME=hr
    ports:
      - "8002:8002"
    networks:
      - erp-network
    restart: unless-stopped

  # SCM Service
  scm-service:
    build:
      context: .
      dockerfile: services/scm-service/Dockerfile
    container_name: erp-scm-service
    environment:
      - PORT=8003
      - SERVICE_NAME=scm
    ports:
      - "8003:8003"
    networks:
      - erp-network
    restart: unless-stopped

  # Manufacturing Service
  manufacturing-service:
    build:
      context: .
      dockerfile: services/m-service/Dockerfile
    container_name: erp-manufacturing-service
    environment:
      - PORT=8004
      - SERVICE_NAME=manufacturing
    ports:
      - "8004:8004"
    networks:
      - erp-network
    restart: unless-stopped

  # CRM Service
  crm-service:
    build:
      context: .
      dockerfile: services/crm-service/Dockerfile
    container_name: erp-crm-service
    environment:
      - PORT=8005
      - SERVICE_NAME=crm
    ports:
      - "8005:8005"
    networks:
      - erp-network
    restart: unless-stopped

  # Projects Service
  projects-service:
    build:
      context: .
      dockerfile: services/pm-service/Dockerfile
    container_name: erp-projects-service
    environment:
      - PORT=8006
      - SERVICE_NAME=projects
    ports:
      - "8006:8006"
    networks:
      - erp-network
    restart: unless-stopped

networks:
  erp-network:
    driver: bridge