// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ChangeRequest struct {
	ID             string    `json:"id"`
	ProjectID      string    `json:"project_id"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Reason         string    `json:"reason"`
	ImpactAnalysis string    `json:"impact_analysis"`
	Status         string    `json:"status"` // e.g. PENDING, APPROVED, REJECTED
	RequestedBy    string    `json:"requested_by"`
	ApprovedBy     *string   `json:"approved_by"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
