// Code generated by CDD Engine. DO NOT EDIT.
package domain

// ProjectStatus represents the ProjectStatus enum
type ProjectStatus string

const (
	ProjectStatusDRAFT     ProjectStatus = "DRAFT"
	ProjectStatusPLANNING  ProjectStatus = "PLANNING"
	ProjectStatusACTIVE    ProjectStatus = "ACTIVE"
	ProjectStatusSUSPENDED ProjectStatus = "SUSPENDED"
	ProjectStatusCOMPLETED ProjectStatus = "COMPLETED"
)

// IsValid returns true if the ProjectStatus is valid
func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusDRAFT:
		return true
	case ProjectStatusPLANNING:
		return true
	case ProjectStatusACTIVE:
		return true
	case ProjectStatusSUSPENDED:
		return true
	case ProjectStatusCOMPLETED:
		return true
	}
	return false
}

// WbsNodeType represents the WbsNodeType enum
type WbsNodeType string

const (
	WbsNodeTypePHASE     WbsNodeType = "PHASE"
	WbsNodeTypeTASK      WbsNodeType = "TASK"
	WbsNodeTypeMILESTONE WbsNodeType = "MILESTONE"
)

// IsValid returns true if the WbsNodeType is valid
func (e WbsNodeType) IsValid() bool {
	switch e {
	case WbsNodeTypePHASE:
		return true
	case WbsNodeTypeTASK:
		return true
	case WbsNodeTypeMILESTONE:
		return true
	}
	return false
}

// BillingMethod represents the BillingMethod enum
type BillingMethod string

const (
	BillingMethodTIME_AND_MATERIALS BillingMethod = "TIME_AND_MATERIALS"
	BillingMethodFIXED_PRICE        BillingMethod = "FIXED_PRICE"
	BillingMethodNON_BILLABLE       BillingMethod = "NON_BILLABLE"
)

// IsValid returns true if the BillingMethod is valid
func (e BillingMethod) IsValid() bool {
	switch e {
	case BillingMethodTIME_AND_MATERIALS:
		return true
	case BillingMethodFIXED_PRICE:
		return true
	case BillingMethodNON_BILLABLE:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
