// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicPrjTimeLogged        = "prj.time.logged"
	TopicPrjMilestoneAchieved = "prj.milestone.achieved"

	// Consumer Events
	TopicHrEmployeeCreated      = "hr.employee.created"
	TopicHrEmployeeTerminated   = "hr.employee.terminated"
	TopicCrmSalesOrderConfirmed = "crm.sales.order.confirmed"
)
