// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicPrjProjectCreated        = "prj.project.created"
	TopicPrjProjectUpdated        = "prj.project.updated"
	TopicPrjProjectStarted        = "prj.project.started"
	TopicPrjProjectCompleted      = "prj.project.completed"
	TopicPrjProjectCancelled      = "prj.project.cancelled"
	TopicPrjProjectDelayed        = "prj.project.delayed"
	TopicPrjTaskCreated           = "prj.task.created"
	TopicPrjTaskAssigned          = "prj.task.assigned"
	TopicPrjTaskStarted           = "prj.task.started"
	TopicPrjTaskCompleted         = "prj.task.completed"
	TopicPrjTaskOverdue           = "prj.task.overdue"
	TopicPrjResourceAllocated     = "prj.resource.allocated"
	TopicPrjResourceReleased      = "prj.resource.released"
	TopicPrjResourceOverallocated = "prj.resource.overallocated"
	TopicPrjTimeLogged            = "prj.time.logged"
	TopicPrjTimeApproved          = "prj.time.approved"
	TopicPrjTimeRejected          = "prj.time.rejected"
	TopicPrjExpenseSubmitted      = "prj.expense.submitted"
	TopicPrjExpenseApproved       = "prj.expense.approved"
	TopicPrjExpenseRejected       = "prj.expense.rejected"
	TopicPrjExpenseIncurred       = "prj.expense.incurred"
	TopicPrjMilestoneAchieved     = "prj.milestone.achieved"
	TopicPrjMilestoneDelayed      = "prj.milestone.delayed"
	TopicPrjCustomOrderCreated    = "prj.custom.order.created"
	TopicPrjMaterialRequested     = "prj.material.requested"

	// Consumer Events
	TopicHrEmployeeAvailable          = "hr.employee.available"
	TopicHrEmployeeSkillsUpdated      = "hr.employee.skills.updated"
	TopicFinBudgetApproved            = "fin.budget.approved"
	TopicFinPaymentReceived           = "fin.payment.received"
	TopicCrmSalesOrderReceived        = "crm.sales.order.received"
	TopicScmMaterialDelivered         = "scm.material.delivered"
	TopicMfgCustomProductionCompleted = "mfg.custom.production.completed"
)
