// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Portfolio struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ManagerID   *string   `json:"manager_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
