// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ProjectDocument struct {
	ID         string    `json:"id"`
	ProjectID  string    `json:"project_id"`
	Name       string    `json:"name"`
	FilePath   string    `json:"file_path"`
	FileSize   int       `json:"file_size"`
	UploadedBy string    `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
