// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ProjectIssue struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Severity    string    `json:"severity"` // e.g. LOW, MEDIUM, HIGH, CRITICAL
	Status      string    `json:"status"`   // e.g. OPEN, IN_PROGRESS, RESOLVED, CLOSED
	AssignedTo  *string   `json:"assigned_to"`
	RaisedBy    string    `json:"raised_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
