// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ResourceAllocation struct {
	ID                   string     `json:"id"`
	ProjectID            string     `json:"project_id"`
	UserID               string     `json:"user_id"`
	Role                 string     `json:"role"`                  // e.g. Manager, Developer, Designer
	AllocationPercentage int        `json:"allocation_percentage"` // e.g. 50 (for 50% allocation)
	StartDate            time.Time  `json:"start_date"`
	EndDate              *time.Time `json:"end_date"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
}
