// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// TimeLogPayload represents the event payload for TimeLogPayload
type TimeLogPayload struct {
	TimeLogID   string          `json:"time_log_id"`
	WbsNodeID   string          `json:"wbs_node_id"`
	EmployeeID  string          `json:"employee_id"`
	HoursSpent  decimal.Decimal `json:"hours_spent"`
	BillingRate decimal.Decimal `json:"billing_rate"`
}
