// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type TimeLog struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"` // Strict multi-tenant data isolation shield
	WbsNodeID        string          `json:"wbs_node_id"`     // Strict Internal Context Reference
	EmployeeID       string          `json:"employee_id"`     // Primitive Ref -> HR.Employee Master (Loose Cross-Domain Link)
	WorkDate         time.Time       `json:"work_date"`       // Partitioning Key Coordinate
	HoursSpent       decimal.Decimal `json:"hours_spent"`
	InternalCostRate decimal.Decimal `json:"internal_cost_rate"` // Snapshot cost from employee record at entry time
	BillingRate      decimal.Decimal `json:"billing_rate"`       // Billable value targeting CRM billing loops
	IsBillable       bool            `json:"is_billable"`
	IsApproved       bool            `json:"is_approved"`
	ApprovedByHrID   *string         `json:"approved_by_hr_id,omitempty"` // Primitive Ref -> HR.Employee Master (Loose Cross-Domain Link)
	CreatedAt        time.Time       `json:"created_at"`                  // Partitioning Key Secondary Coordinate
}
