// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

// TimeLogSubmissionInput represents the event payload for TimeLogSubmissionInput
type TimeLogSubmissionInput struct {
	WbsNodeID        string          `json:"wbs_node_id"`
	WorkDate         time.Time       `json:"work_date"`
	HoursSpent       decimal.Decimal `json:"hours_spent"`
	InternalCostRate decimal.Decimal `json:"internal_cost_rate"`
	BillingRate      decimal.Decimal `json:"billing_rate"`
	IsBillable       bool            `json:"is_billable"`
}
