// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TransactionalOutbox struct {
	ID          string       `json:"id"`
	EventType   string       `json:"event_type"`   // e.g., "prj.milestone.achieved"
	AggregateID string       `json:"aggregate_id"` // Target context entity ID (e.g., WbsNode.id)
	Payload     interface{}  `json:"payload"`
	Status      OutboxStatus `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
}
