// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type WbsNode struct {
	ID                      string           `json:"id"`
	ProjectID               string           `json:"project_id"` // Strict Internal Relational Reference
	ParentNodeID            *string          `json:"parent_node_id,omitempty"`
	WbsDepthLevel           int              `json:"wbs_depth_level"` // Root nodes = 0, tasks increment sequentially
	NodeCode                string           `json:"node_code"`       // e.g., "1.0", "1.1", "1.1.2"
	Title                   string           `json:"title"`
	NodeType                WbsNodeType      `json:"node_type"`
	EstimatedHours          decimal.Decimal  `json:"estimated_hours"`
	BudgetRevenueFunctional *decimal.Decimal `json:"budget_revenue_functional,omitempty"` // Fixed-price milestone cap values
	IsCompleted             bool             `json:"is_completed"`
	Version                 int              `json:"version"` // OCC Shield for progress synchronization locks
	CreatedAt               time.Time        `json:"created_at"`
	UpdatedAt               time.Time        `json:"updated_at"`
}
