// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type CustomerProfile struct {
	ID                 string          `json:"id"`
	LegalEntityID      string          `json:"legal_entity_id"`
	CustomerCode       string          `json:"customer_code"`
	CompanyName        string          `json:"company_name"`
	AccountManagerHrID string          `json:"account_manager_hr_id"`
	Status             CustomerStatus  `json:"status"`
	CreditLimit        decimal.Decimal `json:"credit_limit"`
	Currency           string          `json:"currency"`
	Version            int             `json:"version"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	DeletedAt          *time.Time      `json:"deleted_at,omitempty"`
}
