// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Customer struct {
	ID               string    `json:"id"`
	CompanyName      string    `json:"company_name"`
	ContactName      string    `json:"contact_name"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Status           string    `json:"status"`   // e.g., LEAD, PROSPECT, ACTIVE, INACTIVE
	Category         string    `json:"category"` // e.g., RETAIL, WHOLESALE
	ParentCustomerID *string   `json:"parent_customer_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
