// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type CustomerInteraction struct {
	ID              string    `json:"id"`
	CustomerID      string    `json:"customer_id"`
	Type            string    `json:"type"` // e.g., CALL, EMAIL, MEETING, NOTE
	Subject         string    `json:"subject"`
	Description     string    `json:"description"`
	InteractionDate time.Time `json:"interaction_date"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
}
