// Code generated by CDD Engine. DO NOT EDIT.
package domain

// CustomerStatus represents the CustomerStatus enum
type CustomerStatus string

const (
	CustomerStatusPROSPECT    CustomerStatus = "PROSPECT"
	CustomerStatusACTIVE      CustomerStatus = "ACTIVE"
	CustomerStatusCREDIT_HOLD CustomerStatus = "CREDIT_HOLD"
	CustomerStatusINACTIVE    CustomerStatus = "INACTIVE"
)

// IsValid returns true if the CustomerStatus is valid
func (e CustomerStatus) IsValid() bool {
	switch e {
	case CustomerStatusPROSPECT:
		return true
	case CustomerStatusACTIVE:
		return true
	case CustomerStatusCREDIT_HOLD:
		return true
	case CustomerStatusINACTIVE:
		return true
	}
	return false
}

// PriceBookType represents the PriceBookType enum
type PriceBookType string

const (
	PriceBookTypeSTANDARD          PriceBookType = "STANDARD"
	PriceBookTypeCUSTOMER_SPECIFIC PriceBookType = "CUSTOMER_SPECIFIC"
	PriceBookTypeREGIONAL          PriceBookType = "REGIONAL"
	PriceBookTypePROMOTIONAL       PriceBookType = "PROMOTIONAL"
)

// IsValid returns true if the PriceBookType is valid
func (e PriceBookType) IsValid() bool {
	switch e {
	case PriceBookTypeSTANDARD:
		return true
	case PriceBookTypeCUSTOMER_SPECIFIC:
		return true
	case PriceBookTypeREGIONAL:
		return true
	case PriceBookTypePROMOTIONAL:
		return true
	}
	return false
}

// StrategyEvaluationRule represents the StrategyEvaluationRule enum
type StrategyEvaluationRule string

const (
	StrategyEvaluationRuleFLAT_MARKUP       StrategyEvaluationRule = "FLAT_MARKUP"
	StrategyEvaluationRuleTIERED_VOLUME     StrategyEvaluationRule = "TIERED_VOLUME"
	StrategyEvaluationRuleCUSTOMER_CONTRACT StrategyEvaluationRule = "CUSTOMER_CONTRACT"
	StrategyEvaluationRuleTEMPORAL_DISCOUNT StrategyEvaluationRule = "TEMPORAL_DISCOUNT"
)

// IsValid returns true if the StrategyEvaluationRule is valid
func (e StrategyEvaluationRule) IsValid() bool {
	switch e {
	case StrategyEvaluationRuleFLAT_MARKUP:
		return true
	case StrategyEvaluationRuleTIERED_VOLUME:
		return true
	case StrategyEvaluationRuleCUSTOMER_CONTRACT:
		return true
	case StrategyEvaluationRuleTEMPORAL_DISCOUNT:
		return true
	}
	return false
}

// SalesOrderState represents the SalesOrderState enum
type SalesOrderState string

const (
	SalesOrderStateDRAFT                SalesOrderState = "DRAFT"
	SalesOrderStatePENDING_CREDIT_CHECK SalesOrderState = "PENDING_CREDIT_CHECK"
	SalesOrderStateAPPROVED             SalesOrderState = "APPROVED"
	SalesOrderStatePARTIALLY_FULFILLED  SalesOrderState = "PARTIALLY_FULFILLED"
	SalesOrderStateFULLY_FULFILLED      SalesOrderState = "FULLY_FULFILLED"
	SalesOrderStateINVOICED             SalesOrderState = "INVOICED"
	SalesOrderStateCANCELLED            SalesOrderState = "CANCELLED"
)

// IsValid returns true if the SalesOrderState is valid
func (e SalesOrderState) IsValid() bool {
	switch e {
	case SalesOrderStateDRAFT:
		return true
	case SalesOrderStatePENDING_CREDIT_CHECK:
		return true
	case SalesOrderStateAPPROVED:
		return true
	case SalesOrderStatePARTIALLY_FULFILLED:
		return true
	case SalesOrderStateFULLY_FULFILLED:
		return true
	case SalesOrderStateINVOICED:
		return true
	case SalesOrderStateCANCELLED:
		return true
	}
	return false
}

// BillingTriggerStatus represents the BillingTriggerStatus enum
type BillingTriggerStatus string

const (
	BillingTriggerStatusPENDING   BillingTriggerStatus = "PENDING"
	BillingTriggerStatusPROCESSED BillingTriggerStatus = "PROCESSED"
	BillingTriggerStatusFAILED    BillingTriggerStatus = "FAILED"
)

// IsValid returns true if the BillingTriggerStatus is valid
func (e BillingTriggerStatus) IsValid() bool {
	switch e {
	case BillingTriggerStatusPENDING:
		return true
	case BillingTriggerStatusPROCESSED:
		return true
	case BillingTriggerStatusFAILED:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}

// OpportunityStage represents the OpportunityStage enum
type OpportunityStage string

const (
	OpportunityStageDISCOVERY   OpportunityStage = "DISCOVERY"
	OpportunityStageNEGOTIATION OpportunityStage = "NEGOTIATION"
	OpportunityStageCLOSED_WON  OpportunityStage = "CLOSED_WON"
	OpportunityStageCLOSED_LOST OpportunityStage = "CLOSED_LOST"
)

// IsValid returns true if the OpportunityStage is valid
func (e OpportunityStage) IsValid() bool {
	switch e {
	case OpportunityStageDISCOVERY:
		return true
	case OpportunityStageNEGOTIATION:
		return true
	case OpportunityStageCLOSED_WON:
		return true
	case OpportunityStageCLOSED_LOST:
		return true
	}
	return false
}
