// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicCrmCustomerCreated        = "crm.customer.created"
	TopicCrmCustomerUpdated        = "crm.customer.updated"
	TopicCrmCustomerActivated      = "crm.customer.activated"
	TopicCrmCustomerDeactivated    = "crm.customer.deactivated"
	TopicCrmLeadCreated            = "crm.lead.created"
	TopicCrmLeadQualified          = "crm.lead.qualified"
	TopicCrmLeadConverted          = "crm.lead.converted"
	TopicCrmLeadLost               = "crm.lead.lost"
	TopicCrmOpportunityCreated     = "crm.opportunity.created"
	TopicCrmOpportunityUpdated     = "crm.opportunity.updated"
	TopicCrmOpportunityWon         = "crm.opportunity.won"
	TopicCrmOpportunityLost        = "crm.opportunity.lost"
	TopicCrmSalesOrderCreated      = "crm.sales.order.created"
	TopicCrmSalesOrderUpdated      = "crm.sales.order.updated"
	TopicCrmSalesOrderConfirmed    = "crm.sales.order.confirmed"
	TopicCrmSalesOrderCancelled    = "crm.sales.order.cancelled"
	TopicCrmSalesOrderShipped      = "crm.sales.order.shipped"
	TopicCrmSalesOrderDelivered    = "crm.sales.order.delivered"
	TopicCrmServiceTicketCreated   = "crm.service.ticket.created"
	TopicCrmServiceTicketUpdated   = "crm.service.ticket.updated"
	TopicCrmServiceTicketResolved  = "crm.service.ticket.resolved"
	TopicCrmServiceTicketEscalated = "crm.service.ticket.escalated"
	TopicCrmCampaignLaunched       = "crm.campaign.launched"
	TopicCrmCampaignCompleted      = "crm.campaign.completed"
	TopicCrmEmailSent              = "crm.email.sent"
	TopicCrmEmailOpened            = "crm.email.opened"
	TopicCrmEmailClicked           = "crm.email.clicked"
	TopicCrmSalesOrderReceived     = "crm.sales.order.received"
	TopicCrmCustomerInteractionLogged = "crm.customer.interaction.logged"

	// Consumer Events
	TopicScmInventoryAvailable   = "scm.inventory.available"
	TopicScmShipmentDelivered    = "scm.shipment.delivered"
	TopicFinPaymentReceived      = "fin.payment.received"
	TopicFinCreditCheckCompleted = "fin.credit.check.completed"
	TopicMfgProductionCompleted  = "mfg.production.completed"
	TopicPrjProjectCompleted     = "prj.project.completed"
	TopicHrEmployeePerformance   = "hr.employee.performance"
)
