// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicCrmOrderConfirmed = "crm.order.confirmed"
	TopicCrmOrderCancelled = "crm.order.cancelled"
	TopicCrmBillingAccrued = "crm.billing.accrued"

	// Consumer Events
	TopicPlmMaterialReleased          = "plm.material.released"
	TopicScmOrderShipped              = "scm.order.shipped"
	TopicPrjMilestoneAchieved         = "prj.milestone.achieved"
	TopicCrmCoreCustomerRegistered    = "crm.core.customer.registered"
	TopicCrmCoreCustomerStatusChanged = "crm.core.customer.status_changed"
)
