// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Lead struct {
	ID         string    `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	Company    string    `json:"company"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	Status     string    `json:"status"`
	Score      int       `json:"score"`
	Source     string    `json:"source"`
	CampaignID *string   `json:"campaign_id,omitempty"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
