package domain

const (
	TopicCrmCampaignLaunched           = "crm.campaign.launched"
	TopicCrmCampaignCompleted          = "crm.campaign.completed"
	TopicCrmCustomerInteractionLogged  = "crm.customer.interaction.logged"
	TopicCrmCustomerCreated            = "crm.customer.created"
	TopicCrmCustomerActivated          = "crm.customer.activated"
	TopicCrmCustomerUpdated            = "crm.customer.updated"
	TopicCrmCustomerDeactivated        = "crm.customer.deactivated"
	TopicCrmLeadCreated                = "crm.lead.created"
	TopicCrmLeadQualified              = "crm.lead.qualified"
	TopicCrmLeadLost                   = "crm.lead.lost"
	TopicCrmLeadConverted              = "crm.lead.converted"
	TopicCrmOpportunityCreated         = "crm.opportunity.created"
	TopicCrmOpportunityUpdated         = "crm.opportunity.updated"
	TopicCrmOpportunityWon             = "crm.opportunity.won"
	TopicCrmOpportunityLost            = "crm.opportunity.lost"
	TopicCrmSalesOrderConfirmed        = "crm.sales.order.confirmed"
	TopicCrmSalesOrderCreated          = "crm.sales.order.created"
	TopicCrmSalesOrderUpdated          = "crm.sales.order.updated"
	TopicCrmSalesOrderShipped          = "crm.sales.order.shipped"
	TopicCrmSalesOrderDelivered        = "crm.sales.order.delivered"
	TopicCrmServiceTicketCreated       = "crm.service.ticket.created"
	TopicCrmServiceTicketUpdated       = "crm.service.ticket.updated"
	TopicCrmServiceTicketResolved      = "crm.service.ticket.resolved"
	TopicCrmServiceTicketEscalated      = "crm.service.ticket.escalated"
	TopicCrmEmailSent                  = "crm.email.sent"
	TopicCrmEmailOpened                = "crm.email.opened"
	TopicCrmEmailClicked               = "crm.email.clicked"
	TopicCrmSalesOrderReceived         = "crm.sales.order.received"
	TopicCrmSalesOrderCancelled        = "crm.sales.order.cancelled"

	// Missing Consumer topics
	TopicScmInventoryAvailable   = "scm.inventory.available"
	TopicScmShipmentDelivered     = "scm.shipment.delivered"
	TopicFmPaymentReceived       = "fm.payment.received"
	TopicFmCreditCheckCompleted   = "fm.credit.check.completed"
	TopicMfgProductionCompleted   = "mfg.production.completed"
	TopicPrjProjectCompleted     = "prj.project.completed"
	TopicHrEmployeePerformance   = "hr.employee.performance"
)
