// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Opportunity struct {
	ID          string           `json:"id"`
	CustomerID  string           `json:"customer_id"`
	Title       string           `json:"title"`
	Value       decimal.Decimal  `json:"value"`
	Status      string           `json:"status"`
	Stage       OpportunityStage `json:"stage"`
	Probability decimal.Decimal  `json:"probability"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}
