// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// OrderLinePayload represents the event payload for OrderLinePayload
type OrderLinePayload struct {
	MaterialID      string          `json:"material_id"`
	LineSequence    int             `json:"line_sequence"`
	QuantityOrdered decimal.Decimal `json:"quantity_ordered"`
	UnitSellPrice   decimal.Decimal `json:"unit_sell_price"`
	NetLineAmount   decimal.Decimal `json:"net_line_amount"`
}
