// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PriceBookEntry struct {
	ID                   string          `json:"id"`
	PriceBookID          string          `json:"price_book_id"` // Strict Relational Internal Link
	MaterialID           string          `json:"material_id"`   // Primitive Ref -> PLM.MaterialMaster (Loose Link)
	UnitListPrice        decimal.Decimal `json:"unit_list_price"`
	MinQuantityThreshold decimal.Decimal `json:"min_quantity_threshold"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}
