// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PricingStrategy struct {
	ID                  string                 `json:"id"`
	PriceBookID         string                 `json:"price_book_id"` // Strict Relational Internal Link
	EvaluationRule      StrategyEvaluationRule `json:"evaluation_rule"`
	StrategyVersion     int                    `json:"strategy_version"` // Tracks evolutionary schema changes over historic audits
	ModifierPercentage  decimal.Decimal        `json:"modifier_percentage"`
	ConfigurationMatrix interface{}            `json:"configuration_matrix"` // Houses dynamic structural rules (e.g., volume break boundaries)
	IsActive            bool                   `json:"is_active"`
	CreatedAt           time.Time              `json:"created_at"`
	UpdatedAt           time.Time              `json:"updated_at"`
}
