// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type PriceListItem struct {
	ID          string          `json:"id"`
	PriceListID string          `json:"price_list_id"`
	ProductID   string          `json:"product_id"`
	UnitPrice   decimal.Decimal `json:"unit_price"`
}
