// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type PriceBookHeader struct {
	ID            string        `json:"id"`
	LegalEntityID string        `json:"legal_entity_id"`
	PriceBookCode string        `json:"price_book_code"` // e.g., "PRICING_EU_2026"
	Name          string        `json:"name"`
	Type          PriceBookType `json:"type"`
	StartDate     time.Time     `json:"start_date"`
	EndDate       time.Time     `json:"end_date"`
	IsActive      bool          `json:"is_active"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}
