// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type QuoteLineItem struct {
	ID        string          `json:"id"`
	QuoteID   string          `json:"quote_id"`
	ProductID string          `json:"product_id"` // Primitive Ref -> PLM.MaterialMaster
	Quantity  int             `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}
