// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// QuoteLineItemInput represents the event payload for QuoteLineItemInput
type QuoteLineItemInput struct {
	ProductID string          `json:"product_id"`
	Quantity  int             `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}
