// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Quote struct {
	ID            string          `json:"id"`
	CustomerID    string          `json:"customer_id"`
	Title         string          `json:"title"`
	ValidUntil    time.Time       `json:"valid_until"`
	Status        string          `json:"status"` // e.g., DRAFT, SENT, ACCEPTED, EXPIRED, REJECTED
	TotalAmount   decimal.Decimal `json:"total_amount"`
	OpportunityID *string         `json:"opportunity_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
