// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type SalesOrderItem struct {
	ID           string          `json:"id"`
	SalesOrderID string          `json:"sales_order_id"`
	ProductID    string          `json:"product_id"`
	Quantity     int             `json:"quantity"`
	UnitPrice    decimal.Decimal `json:"unit_price"`
	Discount     decimal.Decimal `json:"discount"`
}
