// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// SalesOrderLineInput represents the event payload for SalesOrderLineInput
type SalesOrderLineInput struct {
	MaterialID      string          `json:"material_id"`
	LineSequence    int             `json:"line_sequence"`
	QuantityOrdered decimal.Decimal `json:"quantity_ordered"`
}
