// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ServiceTicket struct {
	ID          string    `json:"id"`
	CustomerID  string    `json:"customer_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`   // e.g., OPEN, IN_PROGRESS, RESOLVED, ESCALATED
	Priority    string    `json:"priority"` // e.g., LOW, MEDIUM, HIGH, URGENT
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
