// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ServiceTicket struct {
	ID          string    `json:"id"`
	CustomerID  string    `json:"customer_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
