// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TransactionalOutbox struct {
	ID          string       `json:"id"`
	EventType   string       `json:"event_type"`   // e.g., "crm.order.confirmed"
	AggregateID string       `json:"aggregate_id"` // Target context identity token
	Payload     interface{}  `json:"payload"`
	Status      OutboxStatus `json:"status"`
	RetryCount  int          `json:"retry_count"` // Protects Relay worker from poison-pill roadblocks
	CreatedAt   time.Time    `json:"created_at"`
}
