// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Milestone struct {
	ID            string     `json:"id"`
	ProjectID     string     `json:"project_id"`
	Name          string     `json:"name"`
	Description   *string    `json:"description"`
	TargetDate    *time.Time `json:"target_date"`
	CompletionDate *time.Time `json:"completion_date"`
	Status        string     `json:"status"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}
