// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Project struct {
	ID          string     `json:"id"`
	PortfolioID *string    `json:"portfolio_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
	Status      string     `json:"status"` // e.g., PLANNING, ACTIVE, COMPLETED, ON_HOLD, CANCELLED
	BudgetID    *string    `json:"budget_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}
