// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Task struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"project_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	AssignedTo  *string    `json:"assigned_to"`
	Status      string     `json:"status"` // e.g., TODO, IN_PROGRESS, REVIEW, DONE
	StartDate   *time.Time `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}
