// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TaskDependency struct {
	ID              string    `json:"id"`
	TaskID          string    `json:"task_id"`
	DependsOnTaskID string    `json:"depends_on_task_id"`
	DependencyType  string    `json:"dependency_type"` // FS (Finish-to-Start), SS (Start-to-Start), etc.
	CreatedAt       time.Time `json:"created_at"`
}
