// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type TimeEntry struct {
	ID          string          `json:"id"`
	ProjectID   string          `json:"project_id"`
	TaskID      string          `json:"task_id"`
	UserID      string          `json:"user_id"`
	EntryDate   time.Time       `json:"entry_date"`
	Hours       decimal.Decimal `json:"hours"`
	Description string          `json:"description"`
	Status      string          `json:"status"` // e.g., DRAFT, SUBMITTED, APPROVED, REJECTED
	ApprovedBy  *string         `json:"approved_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
