-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for FM Service

CREATE TABLE IF NOT EXISTS currency_rates (
    id UUID PRIMARY KEY NOT NULL,
    from_currency VARCHAR(255) NOT NULL,
    to_currency VARCHAR(255) NOT NULL,
    rate NUMERIC(15, 4) NOT NULL,
    effective_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS fiscal_years (
    id UUID PRIMARY KEY NOT NULL,
    year INT UNIQUE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_closed BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS cost_centers (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    manager_id UUID,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tax_rates (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    rate NUMERIC(15, 4) NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id UUID PRIMARY KEY NOT NULL,
    account_number VARCHAR(255) UNIQUE NOT NULL,
    bank_name VARCHAR(255) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    current_balance NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_credits (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID UNIQUE NOT NULL,
    credit_limit NUMERIC(15, 4) NOT NULL,
    current_balance NUMERIC(15, 4) NOT NULL,
    is_on_hold BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY NOT NULL,
    account_number VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    parent_id UUID REFERENCES accounts(id),
    balance NUMERIC(15, 4) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS budgets (
    id UUID PRIMARY KEY NOT NULL,
    account_id UUID NOT NULL REFERENCES accounts(id),
    cost_center_id UUID REFERENCES cost_centers(id),
    fiscal_year INT NOT NULL,
    period INT NOT NULL,
    allocated_amount NUMERIC(15, 4) NOT NULL,
    spent_amount NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id UUID PRIMARY KEY NOT NULL,
    reference VARCHAR(255) UNIQUE NOT NULL,
    date TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    reversed_by UUID REFERENCES journal_entries(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id UUID PRIMARY KEY NOT NULL,
    entry_id UUID NOT NULL REFERENCES journal_entries(id),
    account_id UUID NOT NULL REFERENCES accounts(id),
    debit_amount NUMERIC(15, 4) NOT NULL,
    credit_amount NUMERIC(15, 4) NOT NULL,
    description TEXT NOT NULL,
    cost_center_id UUID REFERENCES cost_centers(id),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY NOT NULL,
    reference VARCHAR(255) UNIQUE NOT NULL,
    date TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction_lines (
    id UUID PRIMARY KEY NOT NULL,
    transaction_id UUID NOT NULL REFERENCES transactions(id),
    account_id UUID NOT NULL REFERENCES accounts(id),
    debit_amount NUMERIC(15, 4) NOT NULL,
    credit_amount NUMERIC(15, 4) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS invoices (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID NOT NULL,
    invoice_number VARCHAR(255) UNIQUE NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    tax_amount NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS invoice_lines (
    id UUID PRIMARY KEY NOT NULL,
    invoice_id UUID NOT NULL REFERENCES invoices(id),
    description TEXT NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL,
    tax_rate_id UUID REFERENCES tax_rates(id),
    line_total NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_bills (
    id UUID PRIMARY KEY NOT NULL,
    supplier_id UUID NOT NULL REFERENCES suppliers(id),
    bill_number VARCHAR(255) NOT NULL,
    purchase_order_id UUID,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    tax_amount NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_bill_lines (
    id UUID PRIMARY KEY NOT NULL,
    bill_id UUID NOT NULL REFERENCES vendor_bills(id),
    description TEXT NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL,
    tax_rate_id UUID REFERENCES tax_rates(id),
    line_total NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY NOT NULL,
    invoice_id UUID REFERENCES invoices(id),
    bill_id UUID REFERENCES vendor_bills(id),
    bank_account_id UUID REFERENCES bank_accounts(id),
    payment_number VARCHAR(255) UNIQUE NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMERIC(15, 4) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_statements (
    id UUID PRIMARY KEY NOT NULL,
    bank_account_id UUID NOT NULL REFERENCES bank_accounts(id),
    statement_date DATE NOT NULL,
    ending_balance NUMERIC(15, 4) NOT NULL,
    is_reconciled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_statement_lines (
    id UUID PRIMARY KEY NOT NULL,
    statement_id UUID NOT NULL REFERENCES bank_statements(id),
    transaction_date DATE NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(15, 4) NOT NULL,
    is_matched BOOLEAN NOT NULL
);

