-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.financials Service

CREATE TABLE IF NOT EXISTS legal_entities (
    id UUID PRIMARY KEY NOT NULL,
    company_code VARCHAR(255) UNIQUE NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    functional_currency VARCHAR(255) NOT NULL,
    tax_registration_number VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chart_of_accountss (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    account_code VARCHAR(255) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS universal_journal_entries (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    source_module VARCHAR(255) NOT NULL,
    source_document_id UUID NOT NULL,
    posting_date DATE NOT NULL,
    financial_period VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS universal_journal_lines (
    id UUID PRIMARY KEY NOT NULL,
    journal_entry_id UUID NOT NULL REFERENCES universal_journal_entries(id),
    account_id UUID NOT NULL REFERENCES chart_of_accountss(id),
    amount_functional NUMERIC(15, 4) NOT NULL,
    amount_transactional NUMERIC(15, 4) NOT NULL,
    currency_transactional VARCHAR(255) NOT NULL,
    tracking_dimensions VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ar_invoices (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    invoice_number VARCHAR(255) UNIQUE NOT NULL,
    customer_id UUID NOT NULL,
    sales_order_id UUID NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    tax_amount NUMERIC(15, 4) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ap_vendor_bills (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    bill_number VARCHAR(255) UNIQUE NOT NULL,
    vendor_id UUID NOT NULL,
    purchase_order_id UUID NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    tax_amount NUMERIC(15, 4) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS capital_assets (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    asset_tag VARCHAR(255) UNIQUE NOT NULL,
    eam_equipment_id UUID,
    acquisition_cost NUMERIC(15, 4) NOT NULL,
    accumulated_depreciation NUMERIC(15, 4) NOT NULL,
    useful_life_months VARCHAR(255) NOT NULL,
    capitalization_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS depreciation_schedule_lines (
    id UUID PRIMARY KEY NOT NULL,
    fixed_asset_id UUID NOT NULL REFERENCES capital_assets(id),
    fiscal_year VARCHAR(255) NOT NULL,
    period_number VARCHAR(255) NOT NULL,
    depreciation_amount NUMERIC(15, 4) NOT NULL,
    is_posted BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL REFERENCES legal_entities(id),
    account_number VARCHAR(255) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    liquid_balance NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY NOT NULL,
    invoice_id UUID REFERENCES ar_invoices(id),
    bill_id UUID REFERENCES ap_vendor_bills(id),
    bank_account_id UUID REFERENCES bank_accounts(id),
    payment_number VARCHAR(255) NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    amount NUMERIC(15, 4) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_statements (
    id UUID PRIMARY KEY NOT NULL,
    bank_account_id UUID NOT NULL REFERENCES bank_accounts(id),
    statement_date TIMESTAMP NOT NULL,
    ending_balance NUMERIC(15, 4) NOT NULL,
    is_reconciled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_statement_lines (
    id UUID PRIMARY KEY NOT NULL,
    statement_id UUID NOT NULL REFERENCES bank_statements(id),
    transaction_date TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(15, 4) NOT NULL,
    is_matched BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tax_rates (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    rate NUMERIC(15, 4) NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS currency_rates (
    id UUID PRIMARY KEY NOT NULL,
    from_currency VARCHAR(255) NOT NULL,
    to_currency VARCHAR(255) NOT NULL,
    rate NUMERIC(15, 4) NOT NULL,
    effective_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_credits (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID UNIQUE NOT NULL,
    credit_limit NUMERIC(15, 4) NOT NULL,
    current_balance NUMERIC(15, 4) NOT NULL,
    is_on_hold BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

