// Code generated by CDD Engine. DO NOT EDIT.
package domain

// InspectionTriggerType represents the InspectionTriggerType enum
type InspectionTriggerType string

const (
	InspectionTriggerTypeINBOUND_RECEIPT  InspectionTriggerType = "INBOUND_RECEIPT"
	InspectionTriggerTypePRODUCTION_YIELD InspectionTriggerType = "PRODUCTION_YIELD"
	InspectionTriggerTypeCUSTOMER_RETURN  InspectionTriggerType = "CUSTOMER_RETURN"
)

// IsValid returns true if the InspectionTriggerType is valid
func (e InspectionTriggerType) IsValid() bool {
	switch e {
	case InspectionTriggerTypeINBOUND_RECEIPT:
		return true
	case InspectionTriggerTypePRODUCTION_YIELD:
		return true
	case InspectionTriggerTypeCUSTOMER_RETURN:
		return true
	}
	return false
}

// InspectionStatus represents the InspectionStatus enum
type InspectionStatus string

const (
	InspectionStatusPENDING     InspectionStatus = "PENDING"
	InspectionStatusIN_PROGRESS InspectionStatus = "IN_PROGRESS"
	InspectionStatusPASSED      InspectionStatus = "PASSED"
	InspectionStatusFAILED      InspectionStatus = "FAILED"
)

// IsValid returns true if the InspectionStatus is valid
func (e InspectionStatus) IsValid() bool {
	switch e {
	case InspectionStatusPENDING:
		return true
	case InspectionStatusIN_PROGRESS:
		return true
	case InspectionStatusPASSED:
		return true
	case InspectionStatusFAILED:
		return true
	}
	return false
}

// MetricDataType represents the MetricDataType enum
type MetricDataType string

const (
	MetricDataTypeNUMERIC MetricDataType = "NUMERIC"
	MetricDataTypeBOOLEAN MetricDataType = "BOOLEAN"
)

// IsValid returns true if the MetricDataType is valid
func (e MetricDataType) IsValid() bool {
	switch e {
	case MetricDataTypeNUMERIC:
		return true
	case MetricDataTypeBOOLEAN:
		return true
	}
	return false
}

// DispositionAction represents the DispositionAction enum
type DispositionAction string

const (
	DispositionActionRELEASE          DispositionAction = "RELEASE"
	DispositionActionREWORK           DispositionAction = "REWORK"
	DispositionActionSCRAP            DispositionAction = "SCRAP"
	DispositionActionRETURN_TO_VENDOR DispositionAction = "RETURN_TO_VENDOR"
)

// IsValid returns true if the DispositionAction is valid
func (e DispositionAction) IsValid() bool {
	switch e {
	case DispositionActionRELEASE:
		return true
	case DispositionActionREWORK:
		return true
	case DispositionActionSCRAP:
		return true
	case DispositionActionRETURN_TO_VENDOR:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
