// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicQmsInspectionPassed    = "qms.inspection.passed"
	TopicQmsInspectionFailed    = "qms.inspection.failed"
	TopicQmsDispositionExecuted = "qms.disposition.executed"

	// Consumer Events
	TopicScmReceiptStaged  = "scm.receipt.staged"
	TopicMfgYieldProduced  = "mfg.yield.produced"
	TopicHrEmployeeCreated = "hr.employee.created"
)
