// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type InspectionPlan struct {
	ID            string    `json:"id"`
	LegalEntityID string    `json:"legal_entity_id"` // Primitive Ref -> FM.LegalEntity
	MaterialID    string    `json:"material_id"`     // Primitive Ref -> PLM.MaterialMaster
	PlanName      string    `json:"plan_name"`
	IsActive      bool      `json:"is_active"`
	Version       int       `json:"version"` // For Optimistic Concurrency Control (OCC) Shield
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
