// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type InspectionMetricDefinition struct {
	ID                string           `json:"id"`
	InspectionPlanID  string           `json:"inspection_plan_id"`
	MetricKey         string           `json:"metric_key"`
	DisplayName       string           `json:"display_name"`
	DataType          interface{}      `json:"data_type"`
	MinToleranceLimit *decimal.Decimal `json:"min_tolerance_limit,omitempty"`
	MaxToleranceLimit *decimal.Decimal `json:"max_tolerance_limit,omitempty"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
}
