// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// MetricSubmissionInput represents the event payload for MetricSubmissionInput
type MetricSubmissionInput struct {
	MetricDefinitionID string           `json:"metric_definition_id"`
	SampleSequence     int              `json:"sample_sequence"`
	NumericValue       *decimal.Decimal `json:"numeric_value,omitempty"`
	BooleanValue       *bool            `json:"boolean_value,omitempty"`
	IsCompliant        bool             `json:"is_compliant"`
}
