// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type NonConformanceLog struct {
	ID                string             `json:"id"`
	LegalEntityID     string             `json:"legal_entity_id"`
	InspectionID      string             `json:"inspection_id"`
	NcNumber          string             `json:"nc_number"`
	MaterialID        string             `json:"material_id"` // Primitive Ref -> PLM.MaterialMaster
	DefectDescription string             `json:"defect_description"`
	QuantityDefective decimal.Decimal    `json:"quantity_defective"`
	IsQuarantined     bool               `json:"is_quarantined"`
	Disposition       *DispositionAction `json:"disposition,omitempty"`
	DispositionNotes  *string            `json:"disposition_notes,omitempty"`
	ResolvedByHrID    *string            `json:"resolved_by_hr_id,omitempty"` // Primitive Ref -> HR.Employee
	ResolvedAt        *time.Time         `json:"resolved_at,omitempty"`
	Version           int                `json:"version"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}
