// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type QualityInspection struct {
	ID               string      `json:"id"`
	LegalEntityID    string      `json:"legal_entity_id"`
	InspectionPlanID string      `json:"inspection_plan_id"`
	InspectionNumber string      `json:"inspection_number"`
	TriggerSource    interface{} `json:"trigger_source"`
	SourceDocumentID string      `json:"source_document_id"` // Loose Primitive Ref -> SCM Receipt or MFG WorkOrder
	Status           interface{} `json:"status"`
	InspectorHrID    *string     `json:"inspector_hr_id,omitempty"` // Primitive Ref -> HR.Employee
	Version          int         `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}
