// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

// TimeRange represents the event payload for TimeRange
type TimeRange struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}
