-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for Manufacturing Service

CREATE TABLE IF NOT EXISTS bill_of_materialss (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS production_orders (
    id UUID PRIMARY KEY NOT NULL,
    bom_id UUID NOT NULL REFERENCES bill_of_materialss(id),
    product_id UUID NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    scheduled_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

