-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.engineering Service

CREATE TABLE IF NOT EXISTS material_masters (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    sku VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    uom VARCHAR(255) NOT NULL,
    procurement_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    technical_specifications VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bom_headers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    material_id UUID NOT NULL REFERENCES material_masters(id),
    eco_id UUID,
    version_string VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bom_lines (
    id UUID PRIMARY KEY NOT NULL,
    bom_header_id UUID NOT NULL REFERENCES bom_headers(id),
    component_material_id UUID NOT NULL REFERENCES material_masters(id),
    sequence_number VARCHAR(255) NOT NULL,
    quantity_required NUMERIC(15, 4) NOT NULL,
    uom VARCHAR(255) NOT NULL,
    scrap_percentage NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS engineering_change_orders (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    target_material_id UUID NOT NULL REFERENCES material_masters(id),
    eco_number VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    requested_by_hr_id UUID NOT NULL,
    approved_by_hr_id UUID,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    attempt_count VARCHAR(255) NOT NULL
);

