-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.manufacturing Service

CREATE TABLE IF NOT EXISTS work_centers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    work_center_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS routing_stations (
    id UUID PRIMARY KEY NOT NULL,
    work_center_id UUID NOT NULL REFERENCES work_centers(id),
    routing_code VARCHAR(255) NOT NULL,
    station_type VARCHAR(255) NOT NULL,
    equipment_id UUID,
    standard_setup_time_mins VARCHAR(255) NOT NULL,
    standard_run_time_mins VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS work_orders (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    material_id UUID NOT NULL,
    bom_header_id UUID NOT NULL,
    work_order_number VARCHAR(255) NOT NULL,
    quantity_target NUMERIC(15, 4) NOT NULL,
    quantity_produced NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    scheduled_start DATE NOT NULL,
    scheduled_end DATE NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS work_order_routing_states (
    id UUID PRIMARY KEY NOT NULL,
    work_order_id UUID NOT NULL REFERENCES work_orders(id),
    current_station_id UUID NOT NULL REFERENCES routing_stations(id),
    next_suggested_station_id UUID REFERENCES routing_stations(id),
    is_rework_loop BOOLEAN NOT NULL,
    entered_at TIMESTAMP NOT NULL,
    exited_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS material_consumption_logs (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    work_order_id UUID NOT NULL REFERENCES work_orders(id),
    material_id UUID NOT NULL,
    routing_station_id UUID NOT NULL REFERENCES routing_stations(id),
    quantity_consumed NUMERIC(15, 4) NOT NULL,
    warehouse_id UUID NOT NULL,
    operator_hr_id UUID NOT NULL,
    consumed_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS production_yield_logs (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    work_order_id UUID NOT NULL REFERENCES work_orders(id),
    routing_station_id UUID NOT NULL REFERENCES routing_stations(id),
    quantity_good NUMERIC(15, 4) NOT NULL,
    quantity_scrap NUMERIC(15, 4) NOT NULL,
    operator_hr_id UUID NOT NULL,
    recorded_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    attempt_count VARCHAR(255) NOT NULL
);

