// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Account struct {
	ID            string          `json:"id"`
	AccountNumber string          `json:"account_number"`
	Name          string          `json:"name"`
	Type          string          `json:"type"` // e.g., ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE
	ParentID      *string         `json:"parent_id"`
	Balance       decimal.Decimal `json:"balance"`
	Currency      string          `json:"currency"` // e.g., "USD", "EUR"
	IsActive      bool            `json:"is_active"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
