// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type ApVendorBill struct {
	ID              string          `json:"id"`
	LegalEntityID   string          `json:"legal_entity_id"`
	BillNumber      string          `json:"bill_number"`
	VendorID        string          `json:"vendor_id"`         // Loose primitive identity token (SCM Boundary)
	PurchaseOrderID string          `json:"purchase_order_id"` // Loose primitive document token (SCM Boundary)
	TotalAmount     decimal.Decimal `json:"total_amount"`
	TaxAmount       decimal.Decimal `json:"tax_amount"`
	DueDate         time.Time       `json:"due_date"`
	Status          PaymentStatus   `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
