// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type ArInvoice struct {
	ID            string          `json:"id"`
	LegalEntityID string          `json:"legal_entity_id"`
	InvoiceNumber string          `json:"invoice_number"`
	CustomerID    string          `json:"customer_id"`    // Loose primitive identity token (CRM Boundary)
	SalesOrderID  string          `json:"sales_order_id"` // Loose primitive document token (CRM Boundary)
	TotalAmount   decimal.Decimal `json:"total_amount"`
	TaxAmount     decimal.Decimal `json:"tax_amount"`
	DueDate       time.Time       `json:"due_date"`
	Status        PaymentStatus   `json:"status"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
