// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type BankStatementLine struct {
	ID              string          `json:"id"`
	StatementID     string          `json:"statement_id"`
	TransactionDate time.Time       `json:"transaction_date"`
	Description     string          `json:"description"`
	Amount          decimal.Decimal `json:"amount"`
	IsMatched       bool            `json:"is_matched"`
}
