// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type BankAccount struct {
	ID            string          `json:"id"`
	LegalEntityID string          `json:"legal_entity_id"`
	AccountNumber string          `json:"account_number"`
	Currency      string          `json:"currency"` // Local currency of the physical bank branch
	LiquidBalance decimal.Decimal `json:"liquid_balance"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
