// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type BankAccount struct {
	ID             string          `json:"id"`
	AccountNumber  string          `json:"account_number"`
	BankName       string          `json:"bank_name"`
	Currency       string          `json:"currency"`
	CurrentBalance decimal.Decimal `json:"current_balance"`
}
