// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type BankStatement struct {
	ID            string          `json:"id"`
	BankAccountID string          `json:"bank_account_id"`
	StatementDate time.Time       `json:"statement_date"`
	EndingBalance decimal.Decimal `json:"ending_balance"`
	IsReconciled  bool            `json:"is_reconciled"`
}
