// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Budget struct {
	ID              string          `json:"id"`
	AccountID       string          `json:"account_id"`
	CostCenterID    *string         `json:"cost_center_id"`
	FiscalYear      int             `json:"fiscal_year"`
	Period          int             `json:"period"` // Month 1-12
	AllocatedAmount decimal.Decimal `json:"allocated_amount"`
	SpentAmount     decimal.Decimal `json:"spent_amount"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
