// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type CapitalAsset struct {
	ID                      string          `json:"id"`
	LegalEntityID           string          `json:"legal_entity_id"`
	AssetTag                string          `json:"asset_tag"`
	EamEquipmentID          *string         `json:"eam_equipment_id,omitempty"` // Loose primitive identity token (EAM Boundary)
	AcquisitionCost         decimal.Decimal `json:"acquisition_cost"`
	AccumulatedDepreciation decimal.Decimal `json:"accumulated_depreciation"`
	UsefulLifeMonths        int             `json:"useful_life_months"`
	CapitalizationDate      time.Time       `json:"capitalization_date"`
	Status                  AssetState      `json:"status"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
}
