// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ChartOfAccounts struct {
	ID            string      `json:"id"`
	LegalEntityID string      `json:"legal_entity_id"`
	AccountCode   string      `json:"account_code"` // Unique combination with legal_entity_id
	AccountName   string      `json:"account_name"`
	Type          AccountType `json:"type"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}
