// Code generated by CDD Engine. DO NOT EDIT.
package domain

type CostCenter struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ManagerID   *string `json:"manager_id"`
	IsActive    bool    `json:"is_active"`
}
