// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type CurrencyRate struct {
	ID            string          `json:"id"`
	FromCurrency  string          `json:"from_currency"`
	ToCurrency    string          `json:"to_currency"`
	Rate          decimal.Decimal `json:"rate"`
	EffectiveDate time.Time       `json:"effective_date"`
}
