// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type CustomerCredit struct {
	ID             string          `json:"id"`
	CustomerID     string          `json:"customer_id"`
	CreditLimit    decimal.Decimal `json:"credit_limit"`
	CurrentBalance decimal.Decimal `json:"current_balance"`
	IsOnHold       bool            `json:"is_on_hold"`
	Version        int             `json:"version"` // ADDED: Protects against simultaneous deductions
	UpdatedAt      time.Time       `json:"updated_at"`
}
