// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type DepreciationScheduleLine struct {
	ID                 string          `json:"id"`
	FixedAssetID       string          `json:"fixed_asset_id"`
	FiscalYear         int             `json:"fiscal_year"`
	PeriodNumber       int             `json:"period_number"`
	DepreciationAmount decimal.Decimal `json:"depreciation_amount"`
	IsPosted           bool            `json:"is_posted"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}
