// Code generated by CDD Engine. DO NOT EDIT.
package domain

// AccountType represents the AccountType enum
type AccountType string

const (
	AccountTypeASSET     AccountType = "ASSET"
	AccountTypeLIABILITY AccountType = "LIABILITY"
	AccountTypeEQUITY    AccountType = "EQUITY"
	AccountTypeREVENUE   AccountType = "REVENUE"
	AccountTypeEXPENSE   AccountType = "EXPENSE"
)

// IsValid returns true if the AccountType is valid
func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeASSET:
		return true
	case AccountTypeLIABILITY:
		return true
	case AccountTypeEQUITY:
		return true
	case AccountTypeREVENUE:
		return true
	case AccountTypeEXPENSE:
		return true
	}
	return false
}

// LedgerState represents the LedgerState enum
type LedgerState string

const (
	LedgerStateDRAFT    LedgerState = "DRAFT"
	LedgerStatePOSTED   LedgerState = "POSTED"
	LedgerStateREVERSED LedgerState = "REVERSED"
)

// IsValid returns true if the LedgerState is valid
func (e LedgerState) IsValid() bool {
	switch e {
	case LedgerStateDRAFT:
		return true
	case LedgerStatePOSTED:
		return true
	case LedgerStateREVERSED:
		return true
	}
	return false
}

// PaymentStatus represents the PaymentStatus enum
type PaymentStatus string

const (
	PaymentStatusOPEN    PaymentStatus = "OPEN"
	PaymentStatusPARTIAL PaymentStatus = "PARTIAL"
	PaymentStatusPAID    PaymentStatus = "PAID"
)

// IsValid returns true if the PaymentStatus is valid
func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusOPEN:
		return true
	case PaymentStatusPARTIAL:
		return true
	case PaymentStatusPAID:
		return true
	}
	return false
}

// AssetState represents the AssetState enum
type AssetState string

const (
	AssetStateACTIVE            AssetState = "ACTIVE"
	AssetStateFULLY_DEPRECIATED AssetState = "FULLY_DEPRECIATED"
	AssetStateDISPOSED          AssetState = "DISPOSED"
)

// IsValid returns true if the AssetState is valid
func (e AssetState) IsValid() bool {
	switch e {
	case AssetStateACTIVE:
		return true
	case AssetStateFULLY_DEPRECIATED:
		return true
	case AssetStateDISPOSED:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
