// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicFmInvoicePaid                 = "fm.invoice.paid"
	TopicFmVendorPaid                  = "fm.vendor.paid"
	TopicFmCustomerCreditStatusUpdated = "fm.customer.credit_status.updated"
	TopicFmBudgetExceeded              = "fm.budget.exceeded"
	TopicFmAccountBalanceChanged       = "fm.account.balance.changed"
	TopicFmBudgetApproved              = "fm.budget.approved"

	// Consumer Events
	TopicScmReceiptStaged     = "scm.receipt.staged"
	TopicScmOrderShipped      = "scm.order.shipped"
	TopicCrmOrderConfirmed    = "crm.order.confirmed"
	TopicHrPayrollProcessed   = "hr.payroll.processed"
	TopicMfgYieldProduced     = "mfg.yield.produced"
	TopicPrjMilestoneAchieved = "prj.milestone.achieved"
)
