// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicFmInvoiceCreated              = "fm.invoice.created"
	TopicFmInvoiceUpdated              = "fm.invoice.updated"
	TopicFmInvoiceSent                 = "fm.invoice.sent"
	TopicFmInvoicePaid                 = "fm.invoice.paid"
	TopicFmInvoiceOverdue              = "fm.invoice.overdue"
	TopicFmPaymentReceived             = "fm.payment.received"
	TopicFmPaymentProcessed            = "fm.payment.processed"
	TopicFmPaymentFailed               = "fm.payment.failed"
	TopicFmVendorPaymentDue            = "fm.vendor.payment.due"
	TopicFmVendorPaid                  = "fm.vendor.paid"
	TopicFmCustomerCreditStatusUpdated = "fm.customer.credit_status.updated"
	TopicFmBudgetCreated               = "fm.budget.created"
	TopicFmBudgetUpdated               = "fm.budget.updated"
	TopicFmBudgetExceeded              = "fm.budget.exceeded"
	TopicFmAccountCreated              = "fm.account.created"
	TopicFmAccountUpdated              = "fm.account.updated"
	TopicFmAccountBalanceChanged       = "fm.account.balance.changed"
	TopicFmBudgetApproved              = "fm.budget.approved"

	// Consumer Events
	TopicScmReceiptStaged        = "scm.receipt.staged"
	TopicScmOrderShipped         = "scm.order.shipped"
	TopicCrmOrderConfirmed       = "crm.order.confirmed"
	TopicHrPayrollProcessed      = "hr.payroll.processed"
	TopicMfgYieldProduced        = "mfg.yield.produced"
	TopicPrjMilestoneAchieved    = "prj.milestone.achieved"
	TopicHrEmployeeCreated       = "hr.employee.created"
	TopicHrExpenseSubmitted      = "hr.expense.submitted"
	TopicScmPurchaseOrderCreated = "scm.purchase.order.created"
	TopicScmInvoiceReceived      = "scm.invoice.received"
	TopicScmInventoryValued      = "scm.inventory.valued"
	TopicCrmCustomerCreated      = "crm.customer.created"
	TopicMfgProductionCompleted  = "mfg.production.completed"
	TopicMfgMaterialConsumed     = "mfg.material.consumed"
	TopicPrjProjectCreated       = "prj.project.created"
	TopicPrjTimeLogged           = "prj.time.logged"
	TopicPrjExpenseIncurred      = "prj.expense.incurred"
)
