// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicFinInvoiceCreated        = "fin.invoice.created"
	TopicFinInvoiceUpdated        = "fin.invoice.updated"
	TopicFinInvoiceSent           = "fin.invoice.sent"
	TopicFinInvoicePaid           = "fin.invoice.paid"
	TopicFinInvoiceOverdue        = "fin.invoice.overdue"
	TopicFinPaymentReceived       = "fin.payment.received"
	TopicFinPaymentProcessed      = "fin.payment.processed"
	TopicFinPaymentFailed         = "fin.payment.failed"
	TopicFinVendorCreated         = "fin.vendor.created"
	TopicFinVendorUpdated         = "fin.vendor.updated"
	TopicFinVendorPaymentDue      = "fin.vendor.payment.due"
	TopicFinBudgetCreated         = "fin.budget.created"
	TopicFinBudgetUpdated         = "fin.budget.updated"
	TopicFinBudgetExceeded        = "fin.budget.exceeded"
	TopicFinAccountCreated        = "fin.account.created"
	TopicFinAccountUpdated        = "fin.account.updated"
	TopicFinAccountBalanceChanged = "fin.account.balance.changed"
	TopicFinBudgetApproved        = "fin.budget.approved"

	// Consumer Events
	TopicHrEmployeeCreated       = "hr.employee.created"
	TopicHrPayrollProcessed      = "hr.payroll.processed"
	TopicHrExpenseSubmitted      = "hr.expense.submitted"
	TopicScmPurchaseOrderCreated = "scm.purchase.order.created"
	TopicScmInvoiceReceived      = "scm.invoice.received"
	TopicScmInventoryValued      = "scm.inventory.valued"
	TopicCrmSaleCompleted        = "crm.sale.completed"
	TopicCrmCustomerCreated      = "crm.customer.created"
	TopicMfgProductionCompleted  = "mfg.production.completed"
	TopicMfgMaterialConsumed     = "mfg.material.consumed"
	TopicPrjProjectCreated       = "prj.project.created"
	TopicPrjTimeLogged           = "prj.time.logged"
	TopicPrjExpenseIncurred      = "prj.expense.incurred"
)
