// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type FiscalYear struct {
	ID        string    `json:"id"`
	Year      int       `json:"year"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	IsClosed  bool      `json:"is_closed"`
}
