// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type Invoice struct {
	ID            string          `json:"id"`
	CustomerID    string          `json:"customer_id"`
	InvoiceNumber string          `json:"invoice_number"`
	IssueDate     time.Time       `json:"issue_date"`
	DueDate       time.Time       `json:"due_date"`
	TotalAmount   decimal.Decimal `json:"total_amount"`
	TaxAmount     decimal.Decimal `json:"tax_amount"`
	Status        string          `json:"status"` // e.g., DRAFT, SENT, PAID, OVERDUE, VOID
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
