// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type JournalEntryLine struct {
	ID           string          `json:"id"`
	EntryID      string          `json:"entry_id"`
	AccountID    string          `json:"account_id"`
	DebitAmount  decimal.Decimal `json:"debit_amount"`
	CreditAmount decimal.Decimal `json:"credit_amount"`
	Description  string          `json:"description"`
	CostCenterID *string         `json:"cost_center_id"`
	CreatedAt    time.Time       `json:"created_at"`
}
