// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type JournalEntry struct {
	ID          string     `json:"id"`
	Reference   string     `json:"reference"`
	Date        time.Time  `json:"date"`
	Description string     `json:"description"`
	Status      string     `json:"status"` // e.g., PENDING, POSTED, REVERSED
	CreatedBy   string     `json:"created_by"`
	PostedBy    string     `json:"posted_by"`
	PostedAt    *time.Time `json:"posted_at"`
	ReversedBy  *string    `json:"reversed_by"`
	CreatedAt   time.Time  `json:"created_at"`
}
