// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type JournalEntry struct {
	ID          string    `json:"id"`
	Reference   string    `json:"reference"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	Status      string    `json:"status"` // e.g., PENDING, POSTED, REVERSED
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
