// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type KafkaEventInbox struct {
	EventID          string                `json:"event_id"`
	EventType        string                `json:"event_type"`
	ProcessedAt      time.Time             `json:"processed_at"`
	ProcessingStatus EventProcessingStatus `json:"processing_status"`
	Payload          interface{}           `json:"payload"`
}
