// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type LegalEntity struct {
	ID                    string    `json:"id"`
	CompanyCode           string    `json:"company_code"` // e.g., "CORP_DE", "SUBS_US"
	CompanyName           string    `json:"company_name"`
	FunctionalCurrency    string    `json:"functional_currency"` // Strictly enforces ISO 4217 (e.g., "EUR", "USD")
	TaxRegistrationNumber string    `json:"tax_registration_number"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}
