package domain

const (
	TopicFmVendorPaymentDue  = "fm.vendor.payment.due"
	TopicFmInvoiceCreated    = "fm.invoice.created"
	TopicFmInvoiceUpdated    = "fm.invoice.updated"
	TopicFmInvoiceSent       = "fm.invoice.sent"
	TopicFmInvoiceOverdue    = "fm.invoice.overdue"
	TopicFmBudgetCreated     = "fm.budget.created"
	TopicFmBudgetUpdated     = "fm.budget.updated"
	TopicFmPaymentReceived   = "fm.payment.received"
	TopicFmPaymentProcessed  = "fm.payment.processed"
	TopicFmPaymentFailed     = "fm.payment.failed"
	TopicFmAccountCreated    = "fm.account.created"
	TopicFmAccountUpdated    = "fm.account.updated"
	TopicHrEmployeeCreated   = "hr.employee.created"
	TopicHrExpenseSubmitted  = "hr.expense.submitted"
	TopicScmPurchaseOrderCreated = "scm.purchase.order.created"
	TopicScmInventoryValued  = "scm.inventory.valued"
	TopicCrmCustomerCreated  = "crm.customer.created"
	TopicMfgProductionCompleted = "mfg.production.completed"
	TopicMfgMaterialConsumed = "mfg.material.consumed"
	TopicPrjProjectCreated   = "prj.project.created"
	TopicPrjTimeLogged       = "prj.time.logged"
	TopicPrjExpenseIncurred  = "prj.expense.incurred"
	TopicScmInvoiceReceived  = "scm.invoice.received"
)
