// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Payment struct {
	ID            string          `json:"id"`
	InvoiceID     *string         `json:"invoice_id"`
	BillID        *string         `json:"bill_id"`
	PaymentNumber string          `json:"payment_number"`
	PaymentDate   time.Time       `json:"payment_date"`
	Amount        decimal.Decimal `json:"amount"`
	PaymentMethod string          `json:"payment_method"` // e.g., CASH, CHECK, BANK_TRANSFER, CARD
	Status        string          `json:"status"`         // e.g., PENDING, COMPLETED, FAILED
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
