// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type TaxRate struct {
	ID       string          `json:"id"`
	Code     string          `json:"code"`
	Name     string          `json:"name"`
	Rate     decimal.Decimal `json:"rate"`
	IsActive bool            `json:"is_active"`
}
