// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type TransactionLine struct {
	ID            string          `json:"id"`
	TransactionID string          `json:"transaction_id"`
	AccountID     string          `json:"account_id"`
	DebitAmount   decimal.Decimal `json:"debit_amount"`
	CreditAmount  decimal.Decimal `json:"credit_amount"`
	Description   string          `json:"description"`
	CreatedAt     time.Time       `json:"created_at"`
}
