// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type UniversalJournalLine struct {
	ID                    string          `json:"id"`
	JournalEntryID        string          `json:"journal_entry_id"`
	AccountID             string          `json:"account_id"`
	AmountFunctional      decimal.Decimal `json:"amount_functional"`      // Stored natively in LegalEntity.functional_currency
	AmountTransactional   decimal.Decimal `json:"amount_transactional"`   // Original currency value before conversion
	CurrencyTransactional string          `json:"currency_transactional"` // ISO 4217 code of origin transaction
	TrackingDimensions    interface{}     `json:"tracking_dimensions"`
}
