// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type UniversalJournalEntry struct {
	ID               string      `json:"id"`
	LegalEntityID    string      `json:"legal_entity_id"`    // Strict multi-tenant partition shield
	SourceModule     string      `json:"source_module"`      // "SCM", "CRM", "HR", "PRJ", "FM"
	SourceDocumentID string      `json:"source_document_id"` // Primitive reference to external systems
	PostingDate      time.Time   `json:"posting_date"`
	FinancialPeriod  string      `json:"financial_period"` // Format: "YYYY-MM"
	Status           LedgerState `json:"status"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}
