// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type VendorBillLine struct {
	ID          string          `json:"id"`
	BillID      string          `json:"bill_id"`
	Description string          `json:"description"`
	Quantity    int             `json:"quantity"`
	UnitPrice   decimal.Decimal `json:"unit_price"`
	TaxRateID   *string         `json:"tax_rate_id"`
	LineTotal   decimal.Decimal `json:"line_total"`
}
