// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Vendor struct {
	ID          string    `json:"id"`
	VendorCode  string    `json:"vendor_code"`
	VendorName  string    `json:"vendor_name"`
	ContactName string    `json:"contact_name"`
	Email       string    `json:"email"`
	Phone       string    `json:"phone"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
