// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type VendorBill struct {
	ID              string          `json:"id"`
	VendorID        string          `json:"vendor_id"`
	BillNumber      string          `json:"bill_number"`
	PurchaseOrderID *string         `json:"purchase_order_id"`
	IssueDate       time.Time       `json:"issue_date"`
	DueDate         time.Time       `json:"due_date"`
	TotalAmount     decimal.Decimal `json:"total_amount"`
	TaxAmount       decimal.Decimal `json:"tax_amount"`
	Status          string          `json:"status"` // e.g., DRAFT, MATCHED, APPROVED, PAID, VOID
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
