package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"erp-system/cdd-engine/parser"
)

// GenerateGoModels generates Go domain models from parsed service contract
func GenerateGoModels(service *parser.Service, outputDir string) error {
	for _, entity := range service.Entities {
		var buf bytes.Buffer

		// Header
		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))

		// Imports
		buf.WriteString("import (\n")
		hasTime := false
		hasDecimal := false
		for _, f := range entity.Fields {
			if f.Type == "timestamp" || f.Type == "date" {
				hasTime = true
			}
			if f.Type == "decimal" {
				hasDecimal = true
			}
		}
		if hasTime {
			buf.WriteString("\t\"time\"\n")
		}
		if hasDecimal {
			buf.WriteString("\t\"github.com/shopspring/decimal\"\n")
		}
		buf.WriteString(")\n\n")

		// Entity comment
		if entity.Comment != "" {
			buf.WriteString(fmt.Sprintf("// %s\n", entity.Comment))
		}

		// Struct definition
		buf.WriteString(fmt.Sprintf("type %s struct {\n", entity.Name))
		for _, f := range entity.Fields {
			goType := mapCDDTypeToGo(f.Type)
			jsonName := toSnakeCase(f.Name)

			if f.IsOptional {
				goType = "*" + goType
			}

			// Add comments if exist
			commentStr := ""
			if f.Comment != "" {
				commentStr = fmt.Sprintf(" // %s", f.Comment)
			}

			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"` %s\n", toCamelCase(f.Name), goType, jsonName, commentStr))
		}
		buf.WriteString("}\n")

		// Format code
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			// Write unformatted code on error for debugging
			_ = os.WriteFile(filepath.Join(outputDir, toSnakeCase(entity.Name)+".go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format generated Go source: %w", err)
		}

		// Write file
		fileName := toSnakeCase(entity.Name) + ".go"
		err = os.WriteFile(filepath.Join(outputDir, fileName), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write Go source file: %w", err)
		}
	}

	// Generate events topics file if any events are defined
	if len(service.ProducerEvents) > 0 || len(service.ConsumerEvents) > 0 {
		var buf bytes.Buffer
		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))
		buf.WriteString("const (\n")

		if len(service.ProducerEvents) > 0 {
			buf.WriteString("\t// Producer Events\n")
			for _, ev := range service.ProducerEvents {
				constName := "Topic" + toCamelCase(strings.ReplaceAll(ev.Topic, ".", "_"))
				buf.WriteString(fmt.Sprintf("\t%s = \"%s\"\n", constName, ev.Topic))
			}
			buf.WriteString("\n")
		}

		if len(service.ConsumerEvents) > 0 {
			buf.WriteString("\t// Consumer Events\n")
			for _, ev := range service.ConsumerEvents {
				constName := "Topic" + toCamelCase(strings.ReplaceAll(ev.Topic, ".", "_"))
				buf.WriteString(fmt.Sprintf("\t%s = \"%s\"\n", constName, ev.Topic))
			}
		}

		buf.WriteString(")\n")

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			_ = os.WriteFile(filepath.Join(outputDir, "event_topics.go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format generated events topics source: %w", err)
		}

		err = os.WriteFile(filepath.Join(outputDir, "event_topics.go"), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write events topics file: %w", err)
		}
	}

	return nil
}

func mapCDDTypeToGo(cddType string) string {
	switch strings.ToLower(cddType) {
	case "uuid", "string":
		return "string"
	case "decimal":
		return "decimal.Decimal"
	case "boolean":
		return "bool"
	case "timestamp", "date":
		return "time.Time"
	case "integer":
		return "int"
	default:
		return "interface{}"
	}
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		// Treat acronyms cleanly
		if part == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func toSnakeCase(s string) string {
	var res []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			// If previous is not uppercase, insert underscore
			prev := rune(s[i-1])
			if !(prev >= 'A' && prev <= 'Z') {
				res = append(res, '_')
			}
		}
		res = append(res, r)
	}
	return strings.ToLower(string(res))
}
