package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"erp-system/cdd-engine/parser"
)

// GenerateGoModels generates Go domain models from parsed service contract
func GenerateGoModels(service *parser.Service, outputDir string) error {
	// Generate entity structs
	for _, entity := range service.Entities {
		var buf bytes.Buffer

		// Header
		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))

		// Imports
		buf.WriteString("import (\n")
		hasTime := false
		hasDecimal := false
		for _, f := range entity.Fields {
			if f.Type == "timestamp" || f.Type == "date" {
				hasTime = true
			}
			if f.Type == "decimal" {
				hasDecimal = true
			}
		}
		if hasTime {
			buf.WriteString("\t\"time\"\n")
		}
		if hasDecimal {
			buf.WriteString("\t\"github.com/shopspring/decimal\"\n")
		}
		buf.WriteString(")\n\n")

		// Deprecation comment
		if entity.IsDeprecated {
			buf.WriteString(fmt.Sprintf("// Deprecated: %s\n", entity.DeprecationMsg))
		}

		// Entity comment
		if entity.Comment != "" {
			buf.WriteString(fmt.Sprintf("// %s\n", entity.Comment))
		}

		// Struct definition
		buf.WriteString(fmt.Sprintf("type %s struct {\n", entity.Name))
		for _, f := range entity.Fields {
			goType := mapCDDTypeToGo(f.Type)
			jsonName := toSnakeCase(f.Name)

			if f.IsOptional {
				goType = "*" + goType
			}

			// Add json omitempty for optional fields
			jsonTag := fmt.Sprintf("`json:\"%s\"`", jsonName)
			if f.IsOptional {
				jsonTag = fmt.Sprintf("`json:\"%s,omitempty\"`", jsonName)
			}

			// Add deprecated comment
			deprecatedComment := ""
			if f.IsDeprecated {
				deprecatedComment = " // Deprecated"
			}

			// Add comments if exist
			commentStr := ""
			if f.Comment != "" {
				commentStr = fmt.Sprintf(" // %s", f.Comment)
			}

			buf.WriteString(fmt.Sprintf("\t%s %s %s%s%s\n", toCamelCase(f.Name), goType, jsonTag, deprecatedComment, commentStr))
		}
		buf.WriteString("}\n\n")

		// Generate validation function if there are constraints
		hasConstraints := false
		for _, f := range entity.Fields {
			if len(f.Constraints) > 0 {
				hasConstraints = true
				break
			}
		}

		if hasConstraints {
			buf.WriteString(fmt.Sprintf("// Validate validates the %s struct\n", entity.Name))
			buf.WriteString(fmt.Sprintf("func (e *%s) Validate() error {\n", entity.Name))
			for _, f := range entity.Fields {
				for _, c := range f.Constraints {
					fieldName := toCamelCase(f.Name)
					switch c.Type {
					case "min":
						buf.WriteString(fmt.Sprintf("\tif e.%s < %s {\n", fieldName, c.Value))
						buf.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s must be at least %s\")\n", f.Name, c.Value))
						buf.WriteString("\t}\n")
					case "max":
						buf.WriteString(fmt.Sprintf("\tif e.%s > %s {\n", fieldName, c.Value))
						buf.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s must be at most %s\")\n", f.Name, c.Value))
						buf.WriteString("\t}\n")
					case "positive":
						buf.WriteString(fmt.Sprintf("\tif e.%s <= 0 {\n", fieldName))
						buf.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s must be positive\")\n", f.Name))
						buf.WriteString("\t}\n")
					case "min_length":
						buf.WriteString(fmt.Sprintf("\tif len(e.%s) < %s {\n", fieldName, c.Value))
						buf.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s must be at least %s characters\")\n", f.Name, c.Value))
						buf.WriteString("\t}\n")
					case "max_length":
						buf.WriteString(fmt.Sprintf("\tif len(e.%s) > %s {\n", fieldName, c.Value))
						buf.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s must be at most %s characters\")\n", f.Name, c.Value))
						buf.WriteString("\t}\n")
					}
				}
			}
			buf.WriteString("\treturn nil\n")
			buf.WriteString("}\n\n")
		}

		// Format code
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			// Write unformatted code on error for debugging
			_ = os.WriteFile(filepath.Join(outputDir, toSnakeCase(entity.Name)+".go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format generated Go source: %w", err)
		}

		// Write file
		fileName := toSnakeCase(entity.Name) + ".go"
		err = os.WriteFile(filepath.Join(outputDir, fileName), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write Go source file: %w", err)
		}
	}

	// Generate event payload structs
	for _, payload := range service.EventPayloads {
		var buf bytes.Buffer

		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))

		// Imports
		buf.WriteString("import (\n")
		hasTime := false
		hasDecimal := false
		for _, f := range payload.Fields {
			if f.Type == "timestamp" || f.Type == "date" {
				hasTime = true
			}
			if f.Type == "decimal" {
				hasDecimal = true
			}
		}
		if hasTime {
			buf.WriteString("\t\"time\"\n")
		}
		if hasDecimal {
			buf.WriteString("\t\"github.com/shopspring/decimal\"\n")
		}
		buf.WriteString(")\n\n")

		// Struct definition
		buf.WriteString(fmt.Sprintf("// %s represents the event payload for %s\n", payload.Name, payload.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", payload.Name))
		for _, f := range payload.Fields {
			goType := mapCDDTypeToGo(f.Type)
			jsonName := toSnakeCase(f.Name)

			if f.IsOptional {
				goType = "*" + goType
			}

			jsonTag := fmt.Sprintf("`json:\"%s\"`", jsonName)
			if f.IsOptional {
				jsonTag = fmt.Sprintf("`json:\"%s,omitempty\"`", jsonName)
			}

			buf.WriteString(fmt.Sprintf("\t%s %s %s\n", toCamelCase(f.Name), goType, jsonTag))
		}
		buf.WriteString("}\n")

		// Format and write
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			_ = os.WriteFile(filepath.Join(outputDir, toSnakeCase(payload.Name)+".go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format event payload: %w", err)
		}

		fileName := toSnakeCase(payload.Name) + ".go"
		err = os.WriteFile(filepath.Join(outputDir, fileName), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write event payload file: %w", err)
		}
	}

	// Generate enum constants
	if len(service.Enums) > 0 {
		var buf bytes.Buffer

		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))

		for _, enum := range service.Enums {
			buf.WriteString(fmt.Sprintf("// %s represents the %s enum\n", enum.Name, enum.Name))
			buf.WriteString(fmt.Sprintf("type %s string\n\n", enum.Name))
			buf.WriteString("const (\n")
			for _, value := range enum.Values {
				constName := fmt.Sprintf("%s%s", enum.Name, strings.ToUpper(value))
				buf.WriteString(fmt.Sprintf("\t%s %s = \"%s\"\n", constName, enum.Name, value))
			}
			buf.WriteString(")\n\n")

			// Generate IsValid method
			buf.WriteString(fmt.Sprintf("// IsValid returns true if the %s is valid\n", enum.Name))
			buf.WriteString(fmt.Sprintf("func (e %s) IsValid() bool {\n", enum.Name))
			buf.WriteString("\tswitch e {\n")
			for _, value := range enum.Values {
				constName := fmt.Sprintf("%s%s", enum.Name, strings.ToUpper(value))
				buf.WriteString(fmt.Sprintf("\tcase %s:\n", constName))
			}
			buf.WriteString("\t\treturn true\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn false\n")
			buf.WriteString("}\n\n")
		}

		// Format and write
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			_ = os.WriteFile(filepath.Join(outputDir, "enums.go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format enums: %w", err)
		}

		err = os.WriteFile(filepath.Join(outputDir, "enums.go"), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write enums file: %w", err)
		}
	}

	// Generate events topics file if any events are defined
	if len(service.ProducerEvents) > 0 || len(service.ConsumerEvents) > 0 {
		var buf bytes.Buffer
		buf.WriteString(fmt.Sprintf("// Code generated by CDD Engine. DO NOT EDIT.\n"))
		buf.WriteString(fmt.Sprintf("package domain\n\n"))
		buf.WriteString("const (\n")

		if len(service.ProducerEvents) > 0 {
			buf.WriteString("\t// Producer Events\n")
			for _, ev := range service.ProducerEvents {
				constName := "Topic" + toCamelCase(strings.ReplaceAll(ev.Topic, ".", "_"))
				buf.WriteString(fmt.Sprintf("\t%s = \"%s\"\n", constName, ev.Topic))
			}
			buf.WriteString("\n")
		}

		if len(service.ConsumerEvents) > 0 {
			buf.WriteString("\t// Consumer Events\n")
			for _, ev := range service.ConsumerEvents {
				constName := "Topic" + toCamelCase(strings.ReplaceAll(ev.Topic, ".", "_"))
				buf.WriteString(fmt.Sprintf("\t%s = \"%s\"\n", constName, ev.Topic))
			}
		}

		buf.WriteString(")\n")

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			_ = os.WriteFile(filepath.Join(outputDir, "event_topics.go"), buf.Bytes(), 0644)
			return fmt.Errorf("failed to format generated events topics source: %w", err)
		}

		err = os.WriteFile(filepath.Join(outputDir, "event_topics.go"), formatted, 0644)
		if err != nil {
			return fmt.Errorf("failed to write events topics file: %w", err)
		}
	}

	return nil
}

func mapCDDTypeToGo(cddType string) string {
	switch strings.ToLower(cddType) {
	case "uuid", "string":
		return "string"
	case "decimal":
		return "decimal.Decimal"
	case "boolean":
		return "bool"
	case "timestamp", "date":
		return "time.Time"
	case "integer":
		return "int"
	default:
		return "interface{}"
	}
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		// Treat acronyms cleanly
		if part == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func toSnakeCase(s string) string {
	var res []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			// If previous is not uppercase, insert underscore
			prev := rune(s[i-1])
			if !(prev >= 'A' && prev <= 'Z') {
				res = append(res, '_')
			}
		}
		res = append(res, r)
	}
	return strings.ToLower(string(res))
}
