package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"erp-system/cdd-engine/parser"
)

// GenerateSQLMigrations generates PostgreSQL DDL tables from parsed service contract
func GenerateSQLMigrations(service *parser.Service, outputDir string) error {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("-- Code generated by CDD Engine. DO NOT EDIT.\n"))
	buf.WriteString(fmt.Sprintf("-- Database schema for %s Service\n\n", service.Name))

	for _, entity := range service.Entities {
		tableName := toSnakeCase(entity.Name) + "s"
		// Plural exceptions
		if strings.HasSuffix(tableName, "ys") {
			tableName = tableName[:len(tableName)-2] + "ies"
		}

		buf.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))
		
		var fieldsDDL []string
		for _, f := range entity.Fields {
			colName := toSnakeCase(f.Name)
			colType := mapCDDTypeToSQL(f.Name, f.Type)
			
			constraints := ""
			if f.IsPrimary {
				constraints += " PRIMARY KEY"
			}
			if f.IsUnique {
				constraints += " UNIQUE"
			}
			if !f.IsOptional {
				constraints += " NOT NULL"
			}
			
			if f.ReferenceTo != "" {
				// Parse reference: e.g. "User.id" -> "users(id)"
				parts := strings.Split(f.ReferenceTo, ".")
				refTable := toSnakeCase(parts[0]) + "s"
				if strings.HasSuffix(refTable, "ys") {
					refTable = refTable[:len(refTable)-2] + "ies"
				}
				refCol := toSnakeCase(parts[1])
				constraints += fmt.Sprintf(" REFERENCES %s(%s)", refTable, refCol)
			}

			fieldDDL := fmt.Sprintf("    %s %s%s", colName, colType, constraints)
			fieldsDDL = append(fieldsDDL, fieldDDL)
		}
		
		buf.WriteString(strings.Join(fieldsDDL, ",\n"))
		buf.WriteString("\n);\n\n")
	}

	fileName := fmt.Sprintf("schema.sql")
	err := os.WriteFile(filepath.Join(outputDir, fileName), buf.Bytes(), 0644)
	if err != nil {
		return fmt.Errorf("failed to write SQL migration file: %w", err)
	}

	return nil
}

func mapCDDTypeToSQL(fieldName, cddType string) string {
	switch strings.ToLower(cddType) {
	case "uuid":
		return "UUID"
	case "string":
		lowerName := strings.ToLower(fieldName)
		if strings.Contains(lowerName, "description") || strings.Contains(lowerName, "note") || strings.Contains(lowerName, "specifications") {
			return "TEXT"
		}
		return "VARCHAR(255)"
	case "decimal":
		return "NUMERIC(15, 4)"
	case "boolean":
		return "BOOLEAN"
	case "timestamp":
		return "TIMESTAMP"
	case "date":
		return "DATE"
	case "integer":
		return "INT"
	default:
		return "VARCHAR(255)"
	}
}
