// Code generated by CDD Engine. DO NOT EDIT.
package domain

// PurchaseOrderStatus represents the PurchaseOrderStatus enum
type PurchaseOrderStatus string

const (
	PurchaseOrderStatusDRAFT              PurchaseOrderStatus = "DRAFT"
	PurchaseOrderStatusPENDING_APPROVAL   PurchaseOrderStatus = "PENDING_APPROVAL"
	PurchaseOrderStatusAPPROVED           PurchaseOrderStatus = "APPROVED"
	PurchaseOrderStatusPARTIALLY_RECEIVED PurchaseOrderStatus = "PARTIALLY_RECEIVED"
	PurchaseOrderStatusFULLY_RECEIVED     PurchaseOrderStatus = "FULLY_RECEIVED"
	PurchaseOrderStatusCANCELLED          PurchaseOrderStatus = "CANCELLED"
)

// IsValid returns true if the PurchaseOrderStatus is valid
func (e PurchaseOrderStatus) IsValid() bool {
	switch e {
	case PurchaseOrderStatusDRAFT:
	case PurchaseOrderStatusPENDING_APPROVAL:
	case PurchaseOrderStatusAPPROVED:
	case PurchaseOrderStatusPARTIALLY_RECEIVED:
	case PurchaseOrderStatusFULLY_RECEIVED:
	case PurchaseOrderStatusCANCELLED:
		return true
	}
	return false
}

// InventoryTransactionType represents the InventoryTransactionType enum
type InventoryTransactionType string

const (
	InventoryTransactionTypePURCHASE_RECEIPT   InventoryTransactionType = "PURCHASE_RECEIPT"
	InventoryTransactionTypeSALES_SHIPMENT     InventoryTransactionType = "SALES_SHIPMENT"
	InventoryTransactionTypePRODUCTION_ISSUE   InventoryTransactionType = "PRODUCTION_ISSUE"
	InventoryTransactionTypePRODUCTION_RECEIPT InventoryTransactionType = "PRODUCTION_RECEIPT"
	InventoryTransactionTypeCYCLE_COUNT_ADJ    InventoryTransactionType = "CYCLE_COUNT_ADJ"
)

// IsValid returns true if the InventoryTransactionType is valid
func (e InventoryTransactionType) IsValid() bool {
	switch e {
	case InventoryTransactionTypePURCHASE_RECEIPT:
	case InventoryTransactionTypeSALES_SHIPMENT:
	case InventoryTransactionTypePRODUCTION_ISSUE:
	case InventoryTransactionTypePRODUCTION_RECEIPT:
	case InventoryTransactionTypeCYCLE_COUNT_ADJ:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
	case OutboxStatusSENT:
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
