// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicScmReceiptStaged                 = "scm.receipt.staged"
	TopicScmInventoryReservationCompleted = "scm.inventory.reservation.completed"
	TopicScmInventoryReservationFailed    = "scm.inventory.reservation.failed"
	TopicScmOrderShipped                  = "scm.order.shipped"
	TopicScmAssetReceived                 = "scm.asset.received"

	// Consumer Events
	TopicPlmMaterialReleased               = "plm.material.released"
	TopicCrmSalesOrderReservationRequested = "crm.sales.order.reservation_requested"
	TopicCrmSalesOrderCancelled            = "crm.sales.order.cancelled"
	TopicMfgMaterialConsumed               = "mfg.material.consumed"
	TopicMfgYieldProduced                  = "mfg.yield.produced"
	TopicFmVendorPaid                      = "fm.vendor.paid"
)
