// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type InventoryTransaction struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"`
	WarehouseID      string          `json:"warehouse_id"`
	MaterialID       string          `json:"material_id"` // Primitive Ref -> PLM.MaterialMaster
	TransactionType  interface{}     `json:"transaction_type"`
	QuantityDelta    decimal.Decimal `json:"quantity_delta"`
	SourceDocumentID string          `json:"source_document_id"` // Context token (PO ID, Sales Order ID)
	ExecutedByHrID   string          `json:"executed_by_hr_id"`  // Primitive Ref -> HR.Employee
	CreatedAt        time.Time       `json:"created_at"`         // Immutable sub-ledger timestamp logging
}
