// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PurchaseOrder struct {
	ID                    string          `json:"id"`
	LegalEntityID         string          `json:"legal_entity_id"`
	SupplierID            string          `json:"supplier_id"`
	PoNumber              string          `json:"po_number"`
	Status                interface{}     `json:"status"`
	OrderDate             time.Time       `json:"order_date"`
	EstimatedDeliveryDate *time.Time      `json:"estimated_delivery_date,omitempty"`
	TotalGrossValue       decimal.Decimal `json:"total_gross_value"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
	DeletedAt             *time.Time      `json:"deleted_at,omitempty"` // GORM Native Soft Delete Support
}
