// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type PurchaseOrderLine struct {
	ID               string          `json:"id"`
	PurchaseOrderID  string          `json:"purchase_order_id"`
	MaterialID       string          `json:"material_id"` // Primitive Ref -> PLM.MaterialMaster
	QuantityOrdered  decimal.Decimal `json:"quantity_ordered"`
	QuantityReceived decimal.Decimal `json:"quantity_received"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	NetLineAmount    decimal.Decimal `json:"net_line_amount"`
}
