// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type StockBalance struct {
	ID                string          `json:"id"`
	LegalEntityID     string          `json:"legal_entity_id"`
	WarehouseID       string          `json:"warehouse_id"`
	MaterialID        string          `json:"material_id"` // Primitive Ref -> PLM.MaterialMaster
	QuantityOnHand    decimal.Decimal `json:"quantity_on_hand"`
	QuantityAllocated decimal.Decimal `json:"quantity_allocated"`
	QuantityAvailable decimal.Decimal `json:"quantity_available"`
	Version           int             `json:"version"` // Concurrency Verification Shield (Optimistic Locking)
	UpdatedAt         time.Time       `json:"updated_at"`
}
