// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Supplier struct {
	ID               string    `json:"id"`
	LegalEntityID    string    `json:"legal_entity_id"` // Primitive Ref -> FM.LegalEntity
	SupplierCode     string    `json:"supplier_code"`   // Scoped unique constraint inside the tenant
	Name             string    `json:"name"`
	Currency         string    `json:"currency"` // ISO 4217 code
	PaymentTermsDays int       `json:"payment_terms_days"`
	IsActive         bool      `json:"is_active"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
