// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type TransactionalOutbox struct {
	ID          string      `json:"id"`
	EventType   string      `json:"event_type"`
	AggregateID string      `json:"aggregate_id"`
	Payload     interface{} `json:"payload"`
	Status      interface{} `json:"status"`
	RetryCount  int         `json:"retry_count"` // Retry monitor
	CreatedAt   time.Time   `json:"created_at"`
}
