// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Warehouse struct {
	ID              string    `json:"id"`
	LegalEntityID   string    `json:"legal_entity_id"`
	WarehouseCode   string    `json:"warehouse_code"` // e.g., "WH_NORTH"
	Name            string    `json:"name"`
	LocationAddress string    `json:"location_address"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
