-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.logistics Service

CREATE TABLE IF NOT EXISTS locations (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    location_code VARCHAR(255) NOT NULL,
    location_name VARCHAR(255) NOT NULL,
    location_type VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    supplier_code VARCHAR(255) NOT NULL,
    supplier_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_contracts (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    contract_number VARCHAR(255) NOT NULL,
    supplier_id UUID NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_balances (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    location_id UUID NOT NULL,
    material_id UUID NOT NULL,
    quantity_on_hand NUMERIC(15, 4) NOT NULL,
    quantity_reserved NUMERIC(15, 4) NOT NULL,
    quantity_available NUMERIC(15, 4) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    location_id UUID NOT NULL,
    material_id UUID NOT NULL,
    movement_type VARCHAR(255) NOT NULL,
    quantity NUMERIC(15, 4) NOT NULL,
    reference_type VARCHAR(255) NOT NULL,
    reference_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS demand_forecasts (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    material_id UUID NOT NULL,
    forecast_date TIMESTAMP NOT NULL,
    forecast_quantity NUMERIC(15, 4) NOT NULL,
    confidence_level NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_requisitions (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    req_number VARCHAR(255) NOT NULL,
    requester_id UUID NOT NULL,
    request_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_requisition_lines (
    id UUID PRIMARY KEY NOT NULL,
    purchase_requisition_id UUID NOT NULL,
    material_id UUID NOT NULL,
    quantity_requested NUMERIC(15, 4) NOT NULL,
    estimated_unit_price NUMERIC(15, 4) NOT NULL,
    line_total NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    from_location_id UUID NOT NULL,
    to_location_id UUID NOT NULL,
    material_id UUID NOT NULL,
    quantity NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    transferred_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    po_number VARCHAR(255) NOT NULL,
    supplier_id UUID NOT NULL,
    order_date TIMESTAMP NOT NULL,
    expected_delivery TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id UUID PRIMARY KEY NOT NULL,
    purchase_order_id UUID NOT NULL,
    material_id UUID NOT NULL,
    quantity_ordered NUMERIC(15, 4) NOT NULL,
    quantity_received NUMERIC(15, 4) NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL,
    line_total NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS receipts (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    receipt_number VARCHAR(255) NOT NULL,
    purchase_order_id UUID NOT NULL,
    received_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS shipments (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    shipment_number VARCHAR(255) NOT NULL,
    sales_order_id UUID NOT NULL,
    carrier VARCHAR(255) NOT NULL,
    tracking_number VARCHAR(255) NOT NULL,
    shipped_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

