-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.logistics Service

CREATE TABLE IF NOT EXISTS product_categories (
    id UUID PRIMARY KEY NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY NOT NULL,
    product_code VARCHAR(255) UNIQUE NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    product_type VARCHAR(255) NOT NULL,
    category_id UUID REFERENCES product_categories(id),
    unit_of_measure VARCHAR(255) NOT NULL,
    standard_cost NUMERIC(15, 4) NOT NULL,
    list_price NUMERIC(15, 4) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id UUID PRIMARY KEY NOT NULL,
    location_code VARCHAR(255) NOT NULL,
    location_name VARCHAR(255) NOT NULL,
    location_type VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY NOT NULL,
    supplier_code VARCHAR(255) NOT NULL,
    supplier_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_contracts (
    id UUID PRIMARY KEY NOT NULL,
    contract_number VARCHAR(255) UNIQUE NOT NULL,
    supplier_id UUID NOT NULL REFERENCES suppliers(id),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    terms VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL REFERENCES products(id),
    location_id UUID NOT NULL REFERENCES locations(id),
    quantity_on_hand VARCHAR(255) NOT NULL,
    quantity_reserved VARCHAR(255) NOT NULL,
    quantity_available VARCHAR(255) NOT NULL,
    reorder_point VARCHAR(255) NOT NULL,
    maximum_stock VARCHAR(255) NOT NULL,
    unit_cost NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL REFERENCES products(id),
    location_id UUID NOT NULL REFERENCES locations(id),
    movement_type VARCHAR(255) NOT NULL,
    quantity VARCHAR(255) NOT NULL,
    unit_cost NUMERIC(15, 4) NOT NULL,
    reference_type VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id UUID PRIMARY KEY NOT NULL,
    from_location_id UUID NOT NULL REFERENCES locations(id),
    to_location_id UUID NOT NULL REFERENCES locations(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    transferred_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_requisitions (
    id UUID PRIMARY KEY NOT NULL,
    req_number VARCHAR(255) UNIQUE NOT NULL,
    requester_id VARCHAR(255) NOT NULL,
    request_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_requisition_lines (
    id UUID PRIMARY KEY NOT NULL,
    purchase_requisition_id UUID NOT NULL REFERENCES purchase_requisitions(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity_requested VARCHAR(255) NOT NULL,
    estimated_unit_price NUMERIC(15, 4) NOT NULL,
    line_total NUMERIC(15, 4) NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id UUID PRIMARY KEY NOT NULL,
    po_number VARCHAR(255) UNIQUE NOT NULL,
    supplier_id UUID NOT NULL REFERENCES suppliers(id),
    order_date TIMESTAMP NOT NULL,
    expected_delivery TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id UUID PRIMARY KEY NOT NULL,
    purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity_ordered VARCHAR(255) NOT NULL,
    quantity_received VARCHAR(255) NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL,
    line_total NUMERIC(15, 4) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS receipts (
    id UUID PRIMARY KEY NOT NULL,
    receipt_number VARCHAR(255) UNIQUE NOT NULL,
    purchase_order_id UUID REFERENCES purchase_orders(id),
    received_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS receipt_lines (
    id UUID PRIMARY KEY NOT NULL,
    receipt_id UUID NOT NULL REFERENCES receipts(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity_received VARCHAR(255) NOT NULL,
    unit_cost NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS shipments (
    id UUID PRIMARY KEY NOT NULL,
    shipment_number VARCHAR(255) UNIQUE NOT NULL,
    sales_order_id UUID,
    carrier VARCHAR(255) NOT NULL,
    tracking_number VARCHAR(255) NOT NULL,
    shipped_date TIMESTAMP NOT NULL,
    estimated_delivery TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS shipment_lines (
    id UUID PRIMARY KEY NOT NULL,
    shipment_id UUID NOT NULL REFERENCES shipments(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity_shipped VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS demand_forecasts (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL REFERENCES products(id),
    forecast_date TIMESTAMP NOT NULL,
    forecast_quantity VARCHAR(255) NOT NULL,
    confidence_level NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

