-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for SCM Service

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY NOT NULL,
    product_code VARCHAR(255) UNIQUE NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    product_type VARCHAR(255) NOT NULL,
    unit_of_measure VARCHAR(255) NOT NULL,
    standard_cost NUMERIC(15, 4) NOT NULL,
    list_price NUMERIC(15, 4) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id UUID PRIMARY KEY NOT NULL,
    location_code VARCHAR(255) UNIQUE NOT NULL,
    location_name VARCHAR(255) NOT NULL,
    location_type VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL REFERENCES products(id),
    location_id UUID NOT NULL REFERENCES locations(id),
    quantity_on_hand INT NOT NULL,
    quantity_reserved INT NOT NULL,
    quantity_available INT NOT NULL,
    reorder_point INT NOT NULL,
    maximum_stock INT NOT NULL,
    unit_cost NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id UUID PRIMARY KEY NOT NULL,
    product_id UUID NOT NULL REFERENCES products(id),
    location_id UUID NOT NULL REFERENCES locations(id),
    movement_type VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_cost NUMERIC(15, 4) NOT NULL,
    reference_type VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY NOT NULL,
    supplier_code VARCHAR(255) UNIQUE NOT NULL,
    supplier_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id UUID PRIMARY KEY NOT NULL,
    po_number VARCHAR(255) UNIQUE NOT NULL,
    supplier_id UUID NOT NULL REFERENCES suppliers(id),
    order_date DATE NOT NULL,
    expected_delivery DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id UUID PRIMARY KEY NOT NULL,
    purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id),
    product_id UUID NOT NULL REFERENCES products(id),
    quantity_ordered INT NOT NULL,
    quantity_received INT NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL,
    line_total NUMERIC(15, 4) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

