-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.crm.operations Service

CREATE TABLE IF NOT EXISTS customer_profiles (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    customer_code VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    account_manager_hr_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL,
    credit_limit NUMERIC(15, 4) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    category VARCHAR(255),
    parent_customer_id UUID,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_book_headers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    price_book_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS price_book_entries (
    id UUID PRIMARY KEY NOT NULL,
    price_book_id UUID NOT NULL REFERENCES price_book_headers(id),
    material_id UUID NOT NULL,
    unit_list_price NUMERIC(15, 4) NOT NULL,
    min_quantity_threshold NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS pricing_strategies (
    id UUID PRIMARY KEY NOT NULL,
    price_book_id UUID NOT NULL REFERENCES price_book_headers(id),
    evaluation_rule VARCHAR(255) NOT NULL,
    strategy_version VARCHAR(255) NOT NULL,
    modifier_percentage NUMERIC(15, 4) NOT NULL,
    configuration_matrix VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_orders (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    customer_id UUID NOT NULL REFERENCES customer_profiles(id),
    price_book_id UUID NOT NULL REFERENCES price_book_headers(id),
    order_number VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_gross_value NUMERIC(15, 4) NOT NULL,
    total_tax_value NUMERIC(15, 4) NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_order_lines (
    id UUID PRIMARY KEY NOT NULL,
    sales_order_id UUID NOT NULL REFERENCES sales_orders(id),
    material_id UUID NOT NULL,
    line_sequence VARCHAR(255) NOT NULL,
    quantity_ordered NUMERIC(15, 4) NOT NULL,
    quantity_shipped NUMERIC(15, 4) NOT NULL,
    unit_sell_price NUMERIC(15, 4) NOT NULL,
    discount_applied NUMERIC(15, 4) NOT NULL,
    net_line_amount NUMERIC(15, 4) NOT NULL,
    applied_strategy_version VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_triggers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    sales_order_id UUID NOT NULL REFERENCES sales_orders(id),
    source_delivery_document_id UUID NOT NULL,
    billable_amount NUMERIC(15, 4) NOT NULL,
    tax_amount NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    triggered_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS campaigns (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    budget NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    score VARCHAR(255) NOT NULL,
    source VARCHAR(255) NOT NULL,
    campaign_id UUID REFERENCES campaigns(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS opportunities (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID NOT NULL REFERENCES customer_profiles(id),
    title VARCHAR(255) NOT NULL,
    value NUMERIC(15, 4) NOT NULL,
    status VARCHAR(255) NOT NULL,
    stage VARCHAR(255) NOT NULL,
    probability NUMERIC(15, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_interactions (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID NOT NULL REFERENCES customer_profiles(id),
    type VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    interaction_date TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS service_tickets (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID NOT NULL REFERENCES customer_profiles(id),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
    id UUID PRIMARY KEY NOT NULL,
    customer_id UUID NOT NULL REFERENCES customer_profiles(id),
    title VARCHAR(255) NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(15, 4) NOT NULL,
    opportunity_id UUID REFERENCES opportunities(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS quote_line_items (
    id UUID PRIMARY KEY NOT NULL,
    quote_id UUID NOT NULL REFERENCES quotes(id),
    product_id UUID NOT NULL,
    quantity VARCHAR(255) NOT NULL,
    unit_price NUMERIC(15, 4) NOT NULL
);

