// Code generated by CDD Engine. DO NOT EDIT.
package domain

// EquipmentStatus represents the EquipmentStatus enum
type EquipmentStatus string

const (
	EquipmentStatusONLINE         EquipmentStatus = "ONLINE"
	EquipmentStatusOFFLINE_BROKEN EquipmentStatus = "OFFLINE_BROKEN"
	EquipmentStatusIN_MAINTENANCE EquipmentStatus = "IN_MAINTENANCE"
	EquipmentStatusDECOMMISSIONED EquipmentStatus = "DECOMMISSIONED"
)

// IsValid returns true if the EquipmentStatus is valid
func (e EquipmentStatus) IsValid() bool {
	switch e {
	case EquipmentStatusONLINE:
		return true
	case EquipmentStatusOFFLINE_BROKEN:
		return true
	case EquipmentStatusIN_MAINTENANCE:
		return true
	case EquipmentStatusDECOMMISSIONED:
		return true
	}
	return false
}

// WorkOrderPriority represents the WorkOrderPriority enum
type WorkOrderPriority string

const (
	WorkOrderPriorityLOW      WorkOrderPriority = "LOW"
	WorkOrderPriorityMEDIUM   WorkOrderPriority = "MEDIUM"
	WorkOrderPriorityHIGH     WorkOrderPriority = "HIGH"
	WorkOrderPriorityCRITICAL WorkOrderPriority = "CRITICAL"
)

// IsValid returns true if the WorkOrderPriority is valid
func (e WorkOrderPriority) IsValid() bool {
	switch e {
	case WorkOrderPriorityLOW:
		return true
	case WorkOrderPriorityMEDIUM:
		return true
	case WorkOrderPriorityHIGH:
		return true
	case WorkOrderPriorityCRITICAL:
		return true
	}
	return false
}

// WorkOrderStatus represents the WorkOrderStatus enum
type WorkOrderStatus string

const (
	WorkOrderStatusOPEN        WorkOrderStatus = "OPEN"
	WorkOrderStatusASSIGNED    WorkOrderStatus = "ASSIGNED"
	WorkOrderStatusIN_PROGRESS WorkOrderStatus = "IN_PROGRESS"
	WorkOrderStatusRESOLVED    WorkOrderStatus = "RESOLVED"
	WorkOrderStatusCLOSED      WorkOrderStatus = "CLOSED"
)

// IsValid returns true if the WorkOrderStatus is valid
func (e WorkOrderStatus) IsValid() bool {
	switch e {
	case WorkOrderStatusOPEN:
		return true
	case WorkOrderStatusASSIGNED:
		return true
	case WorkOrderStatusIN_PROGRESS:
		return true
	case WorkOrderStatusRESOLVED:
		return true
	case WorkOrderStatusCLOSED:
		return true
	}
	return false
}

// MaintenanceCategory represents the MaintenanceCategory enum
type MaintenanceCategory string

const (
	MaintenanceCategoryREACTIVE     MaintenanceCategory = "REACTIVE"
	MaintenanceCategoryPREVENTATIVE MaintenanceCategory = "PREVENTATIVE"
)

// IsValid returns true if the MaintenanceCategory is valid
func (e MaintenanceCategory) IsValid() bool {
	switch e {
	case MaintenanceCategoryREACTIVE:
		return true
	case MaintenanceCategoryPREVENTATIVE:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
