// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicEamMachineOffline           = "eam.machine.offline"
	TopicEamMachineOnline            = "eam.machine.online"
	TopicEamWorkorderSparesRequested = "eam.workorder.spares_requested"

	// Consumer Events
	TopicScmAssetReceived   = "scm.asset.received"
	TopicFmAssetCapitalized = "fm.asset.capitalized"
	TopicHrEmployeeCreated  = "hr.employee.created"
)
