// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Facility struct {
	ID              string    `json:"id"`
	LegalEntityID   string    `json:"legal_entity_id"` // Primitive Ref -> FM.LegalEntity
	Name            string    `json:"name"`            // Unique within a legal entity
	PhysicalAddress string    `json:"physical_address"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
