// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type KafkaEventInbox struct {
	EventID          string      `json:"event_id"`   // Unique message tracing identity token from Kafka
	EventType        string      `json:"event_type"` // e.g., "scm.asset.received"
	ProcessedAt      time.Time   `json:"processed_at"`
	ProcessingStatus interface{} `json:"processing_status"`
	Payload          interface{} `json:"payload"`
	AttemptCount     int                   `json:"attempt_count"` // Inbound historic tracking configuration dump
}
