// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type PreventativeSchedule struct {
	ID             string     `json:"id"`
	LegalEntityID  string     `json:"legal_entity_id"`
	EquipmentID    string     `json:"equipment_id"`
	Title          string     `json:"title"`
	InstructionSet string     `json:"instruction_set"` // Standard operating procedures for the technician
	IntervalDays   int        `json:"interval_days"`   // Fixed frequency baseline
	LastExecutedAt *time.Time `json:"last_executed_at,omitempty"`
	NextDueDate    time.Time  `json:"next_due_date"` // Monitored by internal Go ticker cron loops
	IsActive       bool       `json:"is_active"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}
