// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type TelemetryIngestBuffer struct {
	ID            string          `json:"id"`
	LegalEntityID string          `json:"legal_entity_id"` // Multitenant context mapping
	EquipmentID   string          `json:"equipment_id"`    // Reference to physical asset
	SensorKey     string          `json:"sensor_key"`      // e.g., "vibration_displacement_mm"
	ReadingValue  decimal.Decimal `json:"reading_value"`
	RecordedAt    time.Time       `json:"recorded_at"` // Volatile timestamp index partitioned away
}
