-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.quality Service

CREATE TABLE IF NOT EXISTS inspection_plans (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    material_id UUID NOT NULL,
    plan_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inspection_metric_definitions (
    id UUID PRIMARY KEY NOT NULL,
    inspection_plan_id UUID NOT NULL REFERENCES inspection_plans(id),
    metric_key VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    data_type VARCHAR(255) NOT NULL,
    min_tolerance_limit NUMERIC(15, 4),
    max_tolerance_limit NUMERIC(15, 4),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS quality_inspections (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    inspection_plan_id UUID NOT NULL REFERENCES inspection_plans(id),
    inspection_number VARCHAR(255) NOT NULL,
    trigger_source VARCHAR(255) NOT NULL,
    source_document_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL,
    inspector_hr_id UUID,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inspection_result_lines (
    id UUID PRIMARY KEY NOT NULL,
    inspection_id UUID NOT NULL REFERENCES quality_inspections(id),
    metric_definition_id UUID NOT NULL REFERENCES inspection_metric_definitions(id),
    sample_sequence VARCHAR(255) NOT NULL,
    measured_numeric_value NUMERIC(15, 4),
    measured_boolean_value BOOLEAN,
    is_compliant BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS non_conformance_logs (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    inspection_id UUID NOT NULL REFERENCES quality_inspections(id),
    nc_number VARCHAR(255) NOT NULL,
    material_id UUID NOT NULL,
    defect_description VARCHAR(255) NOT NULL,
    quantity_defective NUMERIC(15, 4) NOT NULL,
    is_quarantined BOOLEAN NOT NULL,
    disposition VARCHAR(255),
    disposition_notes VARCHAR(255),
    resolved_by_hr_id UUID,
    resolved_at TIMESTAMP,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

