// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type BomLine struct {
	ID                  string          `json:"id"`
	BomHeaderID         string          `json:"bom_header_id"`
	ComponentMaterialID string          `json:"component_material_id"` // Recursive child item consumed
	SequenceNumber      int             `json:"sequence_number"`       // e.g., 10, 20, 30
	QuantityRequired    decimal.Decimal `json:"quantity_required"`
	Uom                 string          `json:"uom"`
	ScrapPercentage     decimal.Decimal `json:"scrap_percentage"` // Expected material loss margin
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}
