// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// BomComponentPayload represents the event payload for BomComponentPayload
type BomComponentPayload struct {
	ComponentMaterialID string          `json:"component_material_id"`
	SequenceNumber      int             `json:"sequence_number"`
	QuantityRequired    decimal.Decimal `json:"quantity_required"`
	Uom                 string          `json:"uom"`
}
