// Code generated by CDD Engine. DO NOT EDIT.
package domain

// ProcurementType represents the ProcurementType enum
type ProcurementType string

const (
	ProcurementTypeMAKE     ProcurementType = "MAKE"
	ProcurementTypeBUY      ProcurementType = "BUY"
	ProcurementTypeASSEMBLE ProcurementType = "ASSEMBLE"
)

// IsValid returns true if the ProcurementType is valid
func (e ProcurementType) IsValid() bool {
	switch e {
	case ProcurementTypeMAKE:
	case ProcurementTypeBUY:
	case ProcurementTypeASSEMBLE:
		return true
	}
	return false
}

// MaterialStatus represents the MaterialStatus enum
type MaterialStatus string

const (
	MaterialStatusACTIVE   MaterialStatus = "ACTIVE"
	MaterialStatusINACTIVE MaterialStatus = "INACTIVE"
	MaterialStatusOBSOLETE MaterialStatus = "OBSOLETE"
)

// IsValid returns true if the MaterialStatus is valid
func (e MaterialStatus) IsValid() bool {
	switch e {
	case MaterialStatusACTIVE:
	case MaterialStatusINACTIVE:
	case MaterialStatusOBSOLETE:
		return true
	}
	return false
}

// BomStatus represents the BomStatus enum
type BomStatus string

const (
	BomStatusDRAFT    BomStatus = "DRAFT"
	BomStatusRELEASED BomStatus = "RELEASED"
	BomStatusOBSOLETE BomStatus = "OBSOLETE"
)

// IsValid returns true if the BomStatus is valid
func (e BomStatus) IsValid() bool {
	switch e {
	case BomStatusDRAFT:
	case BomStatusRELEASED:
	case BomStatusOBSOLETE:
		return true
	}
	return false
}

// EcoStatus represents the EcoStatus enum
type EcoStatus string

const (
	EcoStatusDRAFT       EcoStatus = "DRAFT"
	EcoStatusIN_REVIEW   EcoStatus = "IN_REVIEW"
	EcoStatusAPPROVED    EcoStatus = "APPROVED"
	EcoStatusIMPLEMENTED EcoStatus = "IMPLEMENTED"
	EcoStatusREJECTED    EcoStatus = "REJECTED"
)

// IsValid returns true if the EcoStatus is valid
func (e EcoStatus) IsValid() bool {
	switch e {
	case EcoStatusDRAFT:
	case EcoStatusIN_REVIEW:
	case EcoStatusAPPROVED:
	case EcoStatusIMPLEMENTED:
	case EcoStatusREJECTED:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
	case OutboxStatusSENT:
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
