// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicPlmMaterialReleased  = "plm.material.released"
	TopicPlmMaterialObsoleted = "plm.material.obsoleted"
	TopicPlmBomReleased       = "plm.bom.released"
	TopicPlmEcoImplemented    = "plm.eco.implemented"

	// Consumer Events
	TopicScmReceiptStaged    = "scm.receipt.staged"
	TopicMfgMaterialConsumed = "mfg.material.consumed"
	TopicHrEmployeeCreated   = "hr.employee.created"
)
