-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.projects Service

CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    customer_id UUID NOT NULL,
    project_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    billing_method VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS wbs_nodes (
    id UUID PRIMARY KEY NOT NULL,
    project_id UUID NOT NULL REFERENCES projects(id),
    parent_node_id UUID REFERENCES wbs_nodes(id),
    wbs_depth_level VARCHAR(255) NOT NULL,
    node_code VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    node_type VARCHAR(255) NOT NULL,
    estimated_hours NUMERIC(15, 4) NOT NULL,
    budget_revenue_functional NUMERIC(15, 4),
    is_completed BOOLEAN NOT NULL,
    version VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS time_logs (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    wbs_node_id UUID NOT NULL REFERENCES wbs_nodes(id),
    employee_id UUID NOT NULL,
    work_date DATE NOT NULL,
    hours_spent NUMERIC(15, 4) NOT NULL,
    internal_cost_rate NUMERIC(15, 4) NOT NULL,
    billing_rate NUMERIC(15, 4) NOT NULL,
    is_billable BOOLEAN NOT NULL,
    is_approved BOOLEAN NOT NULL,
    approved_by_hr_id UUID,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    attempt_count VARCHAR(255) NOT NULL
);

