// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type DemandForecast struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"`
	MaterialID       string          `json:"material_id"`
	ForecastDate     time.Time       `json:"forecast_date"`
	ForecastQuantity decimal.Decimal `json:"forecast_quantity"`
	ConfidenceLevel  decimal.Decimal `json:"confidence_level"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
