// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type DemandForecast struct {
	ID               string          `json:"id"`
	ProductID        string          `json:"product_id"`
	ForecastDate     time.Time       `json:"forecast_date"`
	ForecastQuantity int             `json:"forecast_quantity"`
	ConfidenceLevel  decimal.Decimal `json:"confidence_level"`
	Notes            string          `json:"notes"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
