// Code generated by CDD Engine. DO NOT EDIT.
package domain

// PurchaseOrderStatus represents the PurchaseOrderStatus enum
type PurchaseOrderStatus string

const (
	PurchaseOrderStatusDRAFT              PurchaseOrderStatus = "DRAFT"
	PurchaseOrderStatusPENDING_APPROVAL   PurchaseOrderStatus = "PENDING_APPROVAL"
	PurchaseOrderStatusAPPROVED           PurchaseOrderStatus = "APPROVED"
	PurchaseOrderStatusPARTIALLY_RECEIVED PurchaseOrderStatus = "PARTIALLY_RECEIVED"
	PurchaseOrderStatusFULLY_RECEIVED     PurchaseOrderStatus = "FULLY_RECEIVED"
	PurchaseOrderStatusCANCELLED          PurchaseOrderStatus = "CANCELLED"
)

// IsValid returns true if the PurchaseOrderStatus is valid
func (e PurchaseOrderStatus) IsValid() bool {
	switch e {
	case PurchaseOrderStatusDRAFT:
		return true
	case PurchaseOrderStatusPENDING_APPROVAL:
		return true
	case PurchaseOrderStatusAPPROVED:
		return true
	case PurchaseOrderStatusPARTIALLY_RECEIVED:
		return true
	case PurchaseOrderStatusFULLY_RECEIVED:
		return true
	case PurchaseOrderStatusCANCELLED:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
