// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicScmReceiptStaged        = "scm.receipt.staged"
	TopicScmOrderShipped         = "scm.order.shipped"
	TopicScmPurchaseOrderCreated = "scm.purchase.order.created"
	TopicScmShipmentDispatched   = "scm.shipment.dispatched"

	// Consumer Events
	TopicPlmMaterialReleased               = "plm.material.released"
	TopicCrmSalesOrderReservationRequested = "crm.sales.order.reservation_requested"
	TopicMfgYieldProduced                  = "mfg.yield.produced"
	TopicFinVendorPaymentProcessed         = "fin.vendor.payment.processed"
)
