// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicScmProductCreated             = "scm.product.created"
	TopicScmProductUpdated             = "scm.product.updated"
	TopicScmProductDiscontinued        = "scm.product.discontinued"
	TopicScmInventoryReceived          = "scm.inventory.received"
	TopicScmInventoryShipped           = "scm.inventory.shipped"
	TopicScmInventoryAdjusted          = "scm.inventory.adjusted"
	TopicScmInventoryLowStock          = "scm.inventory.low.stock"
	TopicScmInventoryOutOfStock        = "scm.inventory.out.of.stock"
	TopicScmInventoryValued            = "scm.inventory.valued"
	TopicScmPurchaseOrderCreated       = "scm.purchase.order.created"
	TopicScmPurchaseOrderSent          = "scm.purchase.order.sent"
	TopicScmPurchaseOrderReceived      = "scm.purchase.order.received"
	TopicScmPurchaseOrderCancelled     = "scm.purchase.order.cancelled"
	TopicScmVendorCreated              = "scm.vendor.created"
	TopicScmVendorUpdated              = "scm.vendor.updated"
	TopicScmVendorPerformanceEvaluated = "scm.vendor.performance.evaluated"
	TopicScmShipmentCreated            = "scm.shipment.created"
	TopicScmShipmentDispatched         = "scm.shipment.dispatched"
	TopicScmShipmentDelivered          = "scm.shipment.delivered"
	TopicScmShipmentDelayed            = "scm.shipment.delayed"
	TopicScmTrainingRequired           = "scm.training.required"

	// Consumer Events
	TopicCrmSalesOrderCreated      = "crm.sales.order.created"
	TopicCrmCustomerDemandForecast = "crm.customer.demand.forecast"
	TopicMfgMaterialRequired       = "mfg.material.required"
	TopicMfgProductionCompleted    = "mfg.production.completed"
	TopicFinVendorPaymentProcessed = "fin.vendor.payment.processed"
	TopicPrjMaterialRequested      = "prj.material.requested"
)
