// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type InventoryMovement struct {
	ID            string          `json:"id"`
	LegalEntityID string          `json:"legal_entity_id"`
	LocationID    string          `json:"location_id"`
	MaterialID    string          `json:"material_id"`
	MovementType  string          `json:"movement_type"`
	Quantity      decimal.Decimal `json:"quantity"`
	ReferenceType string          `json:"reference_type"`
	ReferenceID   string          `json:"reference_id"`
	CreatedAt     time.Time       `json:"created_at"`
}
