// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type InventoryMovement struct {
	ID            string          `json:"id"`
	ProductID     string          `json:"product_id"`
	LocationID    string          `json:"location_id"`
	MovementType  string          `json:"movement_type"`
	Quantity      int             `json:"quantity"`
	UnitCost      decimal.Decimal `json:"unit_cost"`
	ReferenceType string          `json:"reference_type"`
	ReferenceID   string          `json:"reference_id"`
	Notes         string          `json:"notes"`
	CreatedAt     time.Time       `json:"created_at"`
}
