// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type InventoryItem struct {
	ID                string          `json:"id"`
	ProductID         string          `json:"product_id"`
	LocationID        string          `json:"location_id"`
	QuantityOnHand    int             `json:"quantity_on_hand"`
	QuantityReserved  int             `json:"quantity_reserved"`
	QuantityAvailable int             `json:"quantity_available"`
	ReorderPoint      int             `json:"reorder_point"`
	MaximumStock      int             `json:"maximum_stock"`
	UnitCost          decimal.Decimal `json:"unit_cost"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}
