// Code generated by CDD Engine. DO NOT EDIT.
package domain

type ProductCategory struct {
	ID          string `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
