// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type Product struct {
	ID            string          `json:"id"`
	ProductCode   string          `json:"product_code"`
	ProductName   string          `json:"product_name"`
	Description   string          `json:"description"`
	ProductType   string          `json:"product_type"` // e.g., RAW_MATERIAL, WORK_IN_PROGRESS, FINISHED_GOOD
	CategoryID    *string         `json:"category_id"`
	UnitOfMeasure string          `json:"unit_of_measure"`
	StandardCost  decimal.Decimal `json:"standard_cost"`
	ListPrice     decimal.Decimal `json:"list_price"`
	IsActive      bool            `json:"is_active"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}
