// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PurchaseOrderLine struct {
	ID               string          `json:"id"`
	PurchaseOrderID  string          `json:"purchase_order_id"`
	MaterialID       string          `json:"material_id"`
	QuantityOrdered  decimal.Decimal `json:"quantity_ordered"`
	QuantityReceived decimal.Decimal `json:"quantity_received"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	LineTotal        decimal.Decimal `json:"line_total"`
	CreatedAt        time.Time       `json:"created_at"`
}
