// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type PurchaseRequisition struct {
	ID          string          `json:"id"`
	ReqNumber   string          `json:"req_number"`
	RequesterID string          `json:"requester_id"`
	RequestDate time.Time       `json:"request_date"`
	Status      string          `json:"status"` // e.g., DRAFT, SUBMITTED, APPROVED, REJECTED
	TotalAmount decimal.Decimal `json:"total_amount"`
	Notes       string          `json:"notes"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
