// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PurchaseOrderLine struct {
	ID               string          `json:"id"`
	PurchaseOrderID  string          `json:"purchase_order_id"`
	ProductID        string          `json:"product_id"`
	QuantityOrdered  int             `json:"quantity_ordered"`
	QuantityReceived int             `json:"quantity_received"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	LineTotal        decimal.Decimal `json:"line_total"`
	Description      string          `json:"description"`
	CreatedAt        time.Time       `json:"created_at"`
}
