// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type PurchaseRequisitionLine struct {
	ID                    string          `json:"id"`
	PurchaseRequisitionID string          `json:"purchase_requisition_id"`
	MaterialID            string          `json:"material_id"`
	QuantityRequested     decimal.Decimal `json:"quantity_requested"`
	EstimatedUnitPrice    decimal.Decimal `json:"estimated_unit_price"`
	LineTotal             decimal.Decimal `json:"line_total"`
}
