// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type PurchaseOrder struct {
	ID               string              `json:"id"`
	LegalEntityID    string              `json:"legal_entity_id"`
	PoNumber         string              `json:"po_number"`
	SupplierID       string              `json:"supplier_id"`
	OrderDate        time.Time           `json:"order_date"`
	ExpectedDelivery time.Time           `json:"expected_delivery"`
	Status           PurchaseOrderStatus `json:"status"`
	TotalAmount      decimal.Decimal     `json:"total_amount"`
	CreatedAt        time.Time           `json:"created_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}
