// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Receipt struct {
	ID              string    `json:"id"`
	ReceiptNumber   string    `json:"receipt_number"`
	PurchaseOrderID *string   `json:"purchase_order_id"`
	ReceivedDate    time.Time `json:"received_date"`
	Status          string    `json:"status"` // e.g., PENDING, RECEIVED, CANCELLED
	Notes           string    `json:"notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
