// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ReceiptLine struct {
	ID               string    `json:"id"`
	ReceiptID        string    `json:"receipt_id"`
	ProductID        string    `json:"product_id"`
	QuantityReceived int       `json:"quantity_received"`
	CreatedAt        time.Time `json:"created_at"`
}
