// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// RequisitionLineInput represents the event payload for RequisitionLineInput
type RequisitionLineInput struct {
	MaterialID         string          `json:"material_id"`
	QuantityRequested  decimal.Decimal `json:"quantity_requested"`
	EstimatedUnitPrice decimal.Decimal `json:"estimated_unit_price"`
}
