// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Shipment struct {
	ID             string    `json:"id"`
	LegalEntityID  string    `json:"legal_entity_id"`
	ShipmentNumber string    `json:"shipment_number"`
	SalesOrderID   string    `json:"sales_order_id"`
	Carrier        string    `json:"carrier"`
	TrackingNumber string    `json:"tracking_number"`
	ShippedDate    time.Time `json:"shipped_date"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
