// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ShipmentLine struct {
	ID              string    `json:"id"`
	ShipmentID      string    `json:"shipment_id"`
	ProductID       string    `json:"product_id"`
	QuantityShipped int       `json:"quantity_shipped"`
	CreatedAt       time.Time `json:"created_at"`
}
