// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type StockTransfer struct {
	ID             string     `json:"id"`
	FromLocationID string     `json:"from_location_id"`
	ToLocationID   string     `json:"to_location_id"`
	ProductID      string     `json:"product_id"`
	Quantity       int        `json:"quantity"`
	Status         string     `json:"status"`
	TransferredAt  *time.Time `json:"transferred_at,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}
