// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type StockBalance struct {
	ID                string          `json:"id"`
	LegalEntityID     string          `json:"legal_entity_id"`
	LocationID        string          `json:"location_id"`
	MaterialID        string          `json:"material_id"`
	QuantityOnHand    decimal.Decimal `json:"quantity_on_hand"`
	QuantityReserved  decimal.Decimal `json:"quantity_reserved"`
	QuantityAvailable decimal.Decimal `json:"quantity_available"`
	Version           int             `json:"version"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}
