// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Supplier struct {
	ID            string    `json:"id"`
	LegalEntityID string    `json:"legal_entity_id"`
	SupplierCode  string    `json:"supplier_code"`
	SupplierName  string    `json:"supplier_name"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
