// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type CostingRecord struct {
	ID                   string          `json:"id"`
	ProductionOrderID    string          `json:"production_order_id"`
	StandardMaterialCost decimal.Decimal `json:"standard_material_cost"`
	ActualMaterialCost   decimal.Decimal `json:"actual_material_cost"`
	StandardLaborCost    decimal.Decimal `json:"standard_labor_cost"`
	ActualLaborCost      decimal.Decimal `json:"actual_labor_cost"`
	MaterialVariance     decimal.Decimal `json:"material_variance"`
	LaborVariance        decimal.Decimal `json:"labor_variance"`
}
