// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicMfgProductionScheduled           = "mfg.production.scheduled"
	TopicMfgProductionStarted             = "mfg.production.started"
	TopicMfgProductionCompleted           = "mfg.production.completed"
	TopicMfgProductionDelayed             = "mfg.production.delayed"
	TopicMfgWorkOrderCreated              = "mfg.work.order.created"
	TopicMfgWorkOrderStarted              = "mfg.work.order.started"
	TopicMfgWorkOrderCompleted            = "mfg.work.order.completed"
	TopicMfgWorkOrderCancelled            = "mfg.work.order.cancelled"
	TopicMfgMaterialConsumed              = "mfg.material.consumed"
	TopicMfgMaterialWasted                = "mfg.material.wasted"
	TopicMfgMaterialRequired              = "mfg.material.required"
	TopicMfgQualityInspectionPassed       = "mfg.quality.inspection.passed"
	TopicMfgQualityInspectionFailed       = "mfg.quality.inspection.failed"
	TopicMfgQualityNonConformanceDetected = "mfg.quality.non.conformance.detected"
	TopicMfgMaintenanceScheduled          = "mfg.maintenance.scheduled"
	TopicMfgMaintenanceCompleted          = "mfg.maintenance.completed"
	TopicMfgEquipmentDown                 = "mfg.equipment.down"
	TopicMfgEquipmentUp                   = "mfg.equipment.up"

	// Consumer Events
	TopicScmMaterialReceived    = "scm.material.received"
	TopicScmInventoryUpdated    = "scm.inventory.updated"
	TopicCrmSalesOrderCreated   = "crm.sales.order.created"
	TopicFinCostBudgetAllocated = "fin.cost.budget.allocated"
	TopicHrEmployeeScheduled    = "hr.employee.scheduled"
	TopicPrjCustomOrderCreated  = "prj.custom.order.created"
)
