// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type LaborReport struct {
	ID          string          `json:"id"`
	WorkOrderID string          `json:"work_order_id"`
	EmployeeID  string          `json:"employee_id"`
	HoursWorked decimal.Decimal `json:"hours_worked"`
	Date        time.Time       `json:"date"`
}
