// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type MachineLog struct {
	ID           string    `json:"id"`
	WorkCenterID string    `json:"work_center_id"`
	StatusCode   string    `json:"status_code"`
	Message      string    `json:"message"`
	Timestamp    time.Time `json:"timestamp"`
}
