// Code generated by CDD Engine. DO NOT EDIT.
package domain

import ()

type NonConformance struct {
	ID               string  `json:"id"`
	InspectionID     string  `json:"inspection_id"`
	Description      string  `json:"description"`
	Severity         string  `json:"severity"` // e.g., LOW, MEDIUM, HIGH, CRITICAL
	Status           string  `json:"status"`   // e.g., OPEN, INVESTIGATING, CLOSED
	CorrectiveAction *string `json:"corrective_action"`
}
