// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type ProductionOrder struct {
	ID            string    `json:"id"`
	BomID         string    `json:"bom_id"`
	ProductID     string    `json:"product_id"`
	Quantity      int       `json:"quantity"`
	Status        string    `json:"status"` // e.g., DRAFT, PLANNED, IN_PROGRESS, COMPLETED, CANCELLED
	ScheduledDate time.Time `json:"scheduled_date"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
