// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type QualityInspection struct {
	ID          string    `json:"id"`
	WorkOrderID string    `json:"work_order_id"`
	InspectorID string    `json:"inspector_id"`
	Result      string    `json:"result"` // e.g., PASS, FAIL, REJECT
	Remarks     string    `json:"remarks"`
	InspectedAt time.Time `json:"inspected_at"`
}
