// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

type WorkOrderStatus string

const (
	WorkOrderStatusPending    WorkOrderStatus = "PENDING"
	WorkOrderStatusInProgress WorkOrderStatus = "IN_PROGRESS"
	WorkOrderStatusCompleted  WorkOrderStatus = "COMPLETED"
	WorkOrderStatusBlocked    WorkOrderStatus = "BLOCKED"
)

func (s WorkOrderStatus) IsValid() bool {
	switch s {
	case WorkOrderStatusPending, WorkOrderStatusInProgress, WorkOrderStatusCompleted, WorkOrderStatusBlocked:
		return true
	}
	return false
}

type WorkOrder struct {
	ID                string           `json:"id"`
	ProductionOrderID string           `json:"production_order_id"`
	SequenceNumber    int              `json:"sequence_number"`
	WorkCenterID      string           `json:"work_center_id"`
	ScheduledStart    time.Time        `json:"scheduled_start"`
	ScheduledEnd      time.Time        `json:"scheduled_end"`
	ActualStart       *time.Time       `json:"actual_start"`
	ActualEnd         *time.Time       `json:"actual_end"`
	Status            WorkOrderStatus  `json:"status"` // e.g., PENDING, IN_PROGRESS, COMPLETED, BLOCKED
	LaborHours        *decimal.Decimal `json:"labor_hours"`
	MachineHours      *decimal.Decimal `json:"machine_hours"`
}
