// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type WorkOrder struct {
	ID                string           `json:"id"`
	ProductionOrderID string           `json:"production_order_id"`
	SequenceNumber    int              `json:"sequence_number"`
	WorkCenterID      string           `json:"work_center_id"`
	ScheduledStart    time.Time        `json:"scheduled_start"`
	ScheduledEnd      time.Time        `json:"scheduled_end"`
	ActualStart       *time.Time       `json:"actual_start"`
	ActualEnd         *time.Time       `json:"actual_end"`
	Status            string           `json:"status"` // e.g., PENDING, IN_PROGRESS, COMPLETED, BLOCKED
	LaborHours        *decimal.Decimal `json:"labor_hours"`
	MachineHours      *decimal.Decimal `json:"machine_hours"`
}
