// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type BOMComponent struct {
	ID                 string          `json:"id"`
	BomID              string          `json:"bom_id"`
	ComponentProductID string          `json:"component_product_id"`
	Quantity           decimal.Decimal `json:"quantity"`
	WasteFactor        decimal.Decimal `json:"waste_factor"`
}
