// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// ConsumedItemPayload represents the event payload for ConsumedItemPayload
type ConsumedItemPayload struct {
	MaterialID       string          `json:"material_id"`
	QuantityDeducted decimal.Decimal `json:"quantity_deducted"`
	WarehouseID      string          `json:"warehouse_id"`
}
