// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

// ConsumptionSubmissionInput represents the event payload for ConsumptionSubmissionInput
type ConsumptionSubmissionInput struct {
	MaterialID       string          `json:"material_id"`
	QuantityConsumed decimal.Decimal `json:"quantity_consumed"`
	WarehouseID      string          `json:"warehouse_id"`
	RoutingStationID string          `json:"routing_station_id"`
}
