// Code generated by CDD Engine. DO NOT EDIT.
package domain

// WorkOrderState represents the WorkOrderState enum
type WorkOrderState string

const (
	WorkOrderStateSTAGED      WorkOrderState = "STAGED"
	WorkOrderStateRELEASED    WorkOrderState = "RELEASED"
	WorkOrderStateIN_PROGRESS WorkOrderState = "IN_PROGRESS"
	WorkOrderStateON_HOLD     WorkOrderState = "ON_HOLD"
	WorkOrderStateCOMPLETED   WorkOrderState = "COMPLETED"
	WorkOrderStateREJECTED    WorkOrderState = "REJECTED"
)

// IsValid returns true if the WorkOrderState is valid
func (e WorkOrderState) IsValid() bool {
	switch e {
	case WorkOrderStateSTAGED:
		return true
	case WorkOrderStateRELEASED:
		return true
	case WorkOrderStateIN_PROGRESS:
		return true
	case WorkOrderStateON_HOLD:
		return true
	case WorkOrderStateCOMPLETED:
		return true
	case WorkOrderStateREJECTED:
		return true
	}
	return false
}

// StationType represents the StationType enum
type StationType string

const (
	StationTypeASSEMBLY   StationType = "ASSEMBLY"
	StationTypeMACHINING  StationType = "MACHINING"
	StationTypePACKAGING  StationType = "PACKAGING"
	StationTypeINSPECTION StationType = "INSPECTION"
)

// IsValid returns true if the StationType is valid
func (e StationType) IsValid() bool {
	switch e {
	case StationTypeASSEMBLY:
		return true
	case StationTypeMACHINING:
		return true
	case StationTypePACKAGING:
		return true
	case StationTypeINSPECTION:
		return true
	}
	return false
}

// OutboxStatus represents the OutboxStatus enum
type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

// IsValid returns true if the OutboxStatus is valid
func (e OutboxStatus) IsValid() bool {
	switch e {
	case OutboxStatusPENDING:
		return true
	case OutboxStatusSENT:
		return true
	case OutboxStatusFAILED:
		return true
	}
	return false
}

// EventProcessingStatus represents the EventProcessingStatus enum
type EventProcessingStatus string

const (
	EventProcessingStatusSUCCESS EventProcessingStatus = "SUCCESS"
	EventProcessingStatusFAILED  EventProcessingStatus = "FAILED"
)

// IsValid returns true if the EventProcessingStatus is valid
func (e EventProcessingStatus) IsValid() bool {
	switch e {
	case EventProcessingStatusSUCCESS:
		return true
	case EventProcessingStatusFAILED:
		return true
	}
	return false
}
