// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type Equipment struct {
	ID              string     `json:"id"`
	WorkCenterID    string     `json:"work_center_id"`
	Name            string     `json:"name"`
	Status          string     `json:"status"` // e.g., OPERATIONAL, UNDER_MAINTENANCE, BROKEN
	LastMaintenance *time.Time `json:"last_maintenance"`
	NextMaintenance *time.Time `json:"next_maintenance"`
}
