// Code generated by CDD Engine. DO NOT EDIT.
package domain

const (
	// Producer Events
	TopicMfgProductionStarted  = "mfg.production.started"
	TopicMfgMaterialConsumed   = "mfg.material.consumed"
	TopicMfgYieldProduced      = "mfg.yield.produced"
	TopicMfgWorkOrderCompleted = "mfg.work_order.completed"

	// Consumer Events
	TopicPlmBomReleased      = "plm.bom.released"
	TopicQmsInspectionPassed = "qms.inspection.passed"
	TopicQmsInspectionFailed = "qms.inspection.failed"
	TopicEamMachineOffline   = "eam.machine.offline"
)
