// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type MaintenanceOrder struct {
	ID              string     `json:"id"`
	EquipmentID     string     `json:"equipment_id"`
	Description     string     `json:"description"`
	Status          string     `json:"status"`           // e.g., SCHEDULED, IN_PROGRESS, COMPLETED
	MaintenanceType string     `json:"maintenance_type"` // e.g., PREVENTIVE, CORRECTIVE
	CompletedAt     *time.Time `json:"completed_at"`
}
