// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type MaterialConsumptionLog struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"`
	WorkOrderID      string          `json:"work_order_id"`
	MaterialID       string          `json:"material_id"` // Primitive Ref -> PLM.MaterialMaster
	RoutingStationID string          `json:"routing_station_id"`
	QuantityConsumed decimal.Decimal `json:"quantity_consumed"`
	WarehouseID      string          `json:"warehouse_id"`   // Primitive Ref -> SCM.Warehouse
	OperatorHrID     string          `json:"operator_hr_id"` // Primitive Ref -> HR.Employee
	ConsumedAt       time.Time       `json:"consumed_at"`    // Partitioning Key Coordinate
}
