// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type ProductionYieldLog struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"`
	WorkOrderID      string          `json:"work_order_id"`
	RoutingStationID string          `json:"routing_station_id"`
	QuantityGood     decimal.Decimal `json:"quantity_good"`
	QuantityScrap    decimal.Decimal `json:"quantity_scrap"`
	OperatorHrID     string          `json:"operator_hr_id"` // Primitive Ref -> HR.Employee
	RecordedAt       time.Time       `json:"recorded_at"`    // Partitioning Key Coordinate
}
