// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type RoutingStation struct {
	ID                    string      `json:"id"`
	WorkCenterID          string      `json:"work_center_id"`
	RoutingCode           string      `json:"routing_code"` // e.g., "OP-10", "REWORK-A"
	StationType           StationType `json:"station_type"`
	EquipmentID           *string     `json:"equipment_id,omitempty"` // Primitive Ref -> EAM.Equipment
	StandardSetupTimeMins int         `json:"standard_setup_time_mins"`
	StandardRunTimeMins   int         `json:"standard_run_time_mins"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}
