// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type RoutingOperation struct {
	ID             string          `json:"id"`
	BomID          string          `json:"bom_id"`
	SequenceNumber int             `json:"sequence_number"`
	WorkCenterID   string          `json:"work_center_id"`
	OperationName  string          `json:"operation_name"`
	SetupTime      decimal.Decimal `json:"setup_time"` // in minutes
	RunTime        decimal.Decimal `json:"run_time"`   // in minutes per unit
}
