// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
)

type WorkCenter struct {
	ID            string          `json:"id"`
	Code          string          `json:"code"`
	Name          string          `json:"name"`
	Status        string          `json:"status"` // e.g., ACTIVE, MAINTENANCE, DOWN
	CapacityHours decimal.Decimal `json:"capacity_hours"`
	HourlyRate    decimal.Decimal `json:"hourly_rate"`
}
