// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type WorkCenter struct {
	ID             string    `json:"id"`
	LegalEntityID  string    `json:"legal_entity_id"`  // Primitive Ref -> FM.LegalEntity
	WorkCenterCode string    `json:"work_center_code"` // e.g., "WC-MILLING-01"
	Name           string    `json:"name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
