// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"time"
)

type WorkOrderRoutingState struct {
	ID                     string     `json:"id"`
	WorkOrderID            string     `json:"work_order_id"`
	CurrentStationID       string     `json:"current_station_id"`
	NextSuggestedStationID *string    `json:"next_suggested_station_id,omitempty"`
	IsReworkLoop           bool       `json:"is_rework_loop"`
	EnteredAt              time.Time  `json:"entered_at"`
	ExitedAt               *time.Time `json:"exited_at,omitempty"`
}
