// Code generated by CDD Engine. DO NOT EDIT.
package domain

import (
	"github.com/shopspring/decimal"
	"time"
)

type WorkOrder struct {
	ID               string          `json:"id"`
	LegalEntityID    string          `json:"legal_entity_id"` // Strict multi-tenant data isolation shield
	MaterialID       string          `json:"material_id"`     // Primitive Ref -> PLM.MaterialMaster
	BomHeaderID      string          `json:"bom_header_id"`   // Primitive Ref -> PLM.BomHeader
	WorkOrderNumber  string          `json:"work_order_number"`
	QuantityTarget   decimal.Decimal `json:"quantity_target"`
	QuantityProduced decimal.Decimal `json:"quantity_produced"`
	Status           WorkOrderState  `json:"status"` // Managed strictly via State Transition interface gates
	ScheduledStart   time.Time       `json:"scheduled_start"`
	ScheduledEnd     time.Time       `json:"scheduled_end"`
	Version          int             `json:"version"` // Concurrency Verification Shield (Optimistic Locking)
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
