-- Code generated by CDD Engine. DO NOT EDIT.
-- Database schema for erp.eam Service

CREATE TABLE IF NOT EXISTS facilities (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    physical_address VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS equipments (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    facility_id UUID NOT NULL REFERENCES facilities(id),
    asset_tag VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) NOT NULL,
    financial_asset_id UUID,
    status VARCHAR(255) NOT NULL,
    installation_date DATE NOT NULL,
    technical_specifications VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS maintenance_work_orders (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    equipment_id UUID NOT NULL REFERENCES equipments(id),
    ticket_number VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    reported_by_hr_id UUID NOT NULL,
    assigned_tech_hr_id UUID,
    reported_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    resolved_at TIMESTAMP,
    resolution_notes VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS preventative_schedules (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    equipment_id UUID NOT NULL REFERENCES equipments(id),
    title VARCHAR(255) NOT NULL,
    instruction_set VARCHAR(255) NOT NULL,
    interval_days VARCHAR(255) NOT NULL,
    last_executed_at TIMESTAMP,
    next_due_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS telemetry_ingest_buffers (
    id UUID PRIMARY KEY NOT NULL,
    legal_entity_id UUID NOT NULL,
    equipment_id UUID NOT NULL REFERENCES equipments(id),
    sensor_key VARCHAR(255) NOT NULL,
    reading_value NUMERIC(15, 4) NOT NULL,
    recorded_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactional_outboxs (
    id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS kafka_event_inboxs (
    event_id UUID PRIMARY KEY NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL
);

